<?php 
	require_once('../../init.php');
	
	$term = $_GET['term'];
	
	/*$service = array(
		'service' => 'transpera.relation.select.workflow',
		'conn' => 'ayconn',
		'relation' => '`profiles`',
		'sqlprj' => 'distinct `org`',
		'sqlcnd' => "where `ustatus`='A' and  limit 50",
		'type' => 'profile',
		'successmsg' => 'Registration college information given successfully',
		'output' => array('result' => 'colleges'),
		'ismap' => false
	);
	
	$memory = Snowblozm::run($service, $memory);
	$colleges = $memory['colleges'];
	$source = array();
	
	foreach($colleges as $value)
		array_push($source, $value['org']);
	
	echo json_encode($source);
	exit;
	*/
	
	$colleges = array(
		"A. D. Patel Institute of Technology, Vallabh Vidyanagar",
		"Jatipita College Of Engineering, Adilabad",
		"Tolani F.G. Polytechnic, Adipur",
		"Agartala, NIT",
		"Dr. MPS Memorial College of Business Studies, Agra",
		"F.E.T.Agra College, Agra",
		"Agra Public Institute of Technology & Computer Education, Agra",
		"Anand Engineering College, Agra",
		"Babu Mohan Lal Arya Smarak Engineering College, Agra",
		"Dayalbagh Educational Institute, Agra",
		"Hindustan College of Science & Technology, Agra",
		"Institute of Engineering and Technology, Agra",
		"R.B.S. College, Agra",
		"Mudra Institute of Communications, Ahmedabad",
		"Ahmedabad, IIM",
		"L.D. College of Engineering, Ahmedabad",
		"Nirma University Of Science & Technology, Ahmedabad",
		"School of Building Science and Technology, Ahmedabad",
		"Amritwahini College of Engineering, Ahmednagar",
		"College of Agricultural Engineering, Ahmednagar",
		"Padmashri Vikhe Patil College of Engineering, Ahmednagar",
		"Parvara Rural College of Engineering, Ahmednagar",
		"Sanjivani .E S's College of Engineering, Ahmednagar",
		"Ajmer Engineering College, Ajmer",
		"College of Agricultural Engineering, Akola",
		"S.S.E.Society's College of Engineering and Technology, Akola",
		"Aligarh Muslim University, Aligarh",
		"Institute Of Technology Management, Aligarh",
		"Aligarh College of Enggineering, Aligarh",
		"Institute of Petroleum Studies & Chemical Engineering, Aligarh",
		"Shivdan Singh Institute of Technology and Management, Aligarh",
		"Ewing Christian Institute Of Management And Technology, Allahabad",
		"HCL Career Development Center, Allahabad",
		"IIIT ( Amethi campus ), Allahabad",
		"LDC Institute Of Technical Studies, Allahabad",
		"Shambhunath Institute of Enggineering & Technology, Allahabad",
		"United College of Engineering & Reasearch, Allahabad",
		"United Institute Of Technology, Allahabad",
		"Allahabad Agricultural Institute, Allahabad",
		"Allahabad University, Allahabad",
		"B.B.S. College of Engg. & Technology, Allahabad",
		"IIIT, Allahabad",
		"Institute of Engg. & Rural Technology, Allahabad",
		"J.K. Institute of Applied Physics and Technology, Allahabad",
		"MNNIT, Allahabad",
		"United College Of Engineering & Research, Allahabad",
		"Kumaon Engineering College, Almora",
		"Lord's Institute of Engineering and Technology for Women, Alwar",
		"Ceramic Institute of Technology & Research in Ceramic Glass, Cem, Alwar",
		"Institute of Engineering & Technology, Alwar",
		"Laxmi Devi Institute of Engineering & Technology, Alwar",
		"St. Margaret Engineering College, Alwar",
		"MEPCO Schlenk Enginering College, Amartur",
		"Maharishi Markendeshwar Engineering College, Ambala City",
		"Ambala College of Engineering & Applied Research, Ambala",
		"Ambala College of Engineering and Applied Research, Ambala",
		"Prasarak Mandal's College Of engg & Tech, Amravati",
		"Govt. College of Engineering, Amravati",
		"Sipna Shikshan Prasarak Mandal's College Of engg & Tech, Amravati",
		"Guru Nanak Dev University, Amritsar",
		"Khalsa College, Amritsar",
		"Dadi Institute Of Engineering and Technology, Anakapalle",
		"A.D. Patel Institute of Technology, Anand",
		"Sri Balaji P.G College, Anantapur",
		"College of Engineering, Jawaharlal Nehru Technological Univer, Anantpur",
		"Annamalai Nagar, Annamaili University",
		"Faculty of Engineering and Technology, Annamalainagar",
		"Universidad de Buenos Aires, Argentina",
		"Asansol Engineering College, Asansol",
		"Georgia Institute of Technology, Atlanta",
		"Centre for Elec. Design & Tech., Dept of Phy., Marathwada U, Aurangabad",
		"G S Mandal's College of Engineering, Aurangabad",
		"G.S. Mandal's Marathwada Institute of Technology, Aurangabad",
		"Government College of Engineering, Aurangabad",
		"Mahatma Gandhi Mission's Jawaharlal Nehru College of Engine, Aurangabad",
		"P.E.S. College of Engineering, Aurangabad",
		"Pandit Jawaharlal Nehru College of Engineering, Aurangabad",
		"James Cook University, Australia",
		"University of Adelaide, Australia",
		"Pharamcy College, Azamgarh",
		"V Y W S College of Engineering Badnera, Badnera",
		"Basaveshwar Engineering College, Bagalkot",
		"PDM College Of Engg., Bahadurgarh",
		"Agricultural University, Banaskantha",
		"Banasthali, Banasthali",
		"Kali Charan Nigam Institute of Technology, Banda",
		"Alliance Business Academy, Bangalore",
		"Alliance Business School, Bangalore",
		"AMC Engineering College, Bangalore",
		"Amrita School of Engineering, Bangalore",
		"National Power Training Institute, Bangalore",
		"Welingkar Institute of Management Development and Research, Bangalore",
		"Xavier Institute of Management and Entrepreneurship, Bangalore",
		"B M S College of Engineering, Bangalore",
		"Bangalore College of Engineering and Technology, Bangalore",
		"Bangalore Institute of Technology, Bangalore",
		"Bangalore Technical Foundation Trust, Bangalore",
		"C.M.R. Institute of Technology, Bangalore",
		"Dayananda Sagar College of Engineering, Bangalore",
		"Dr. Ambedkar Institute of Technology, Bangalore",
		"Government S.K.S.J. Technology Institute, Bangalore",
		"ICFAI-Institute of Science and Technology, Bangalore",
		"IIIT, Bangalore",
		"IIM, Bangalore",
		"Indian Institute of Science, Bangalore",
		"International college of science and information, Bangalore",
		"JSS Acdemy of Technical Education, Bangalore",
		"Kammavari Sangham Institute of Technology, Bangalore",
		"M.S. Ramaiah Institute of Technology, Bangalore",
		"M.V.J. College of Engineering, Bangalore",
		"National Law University, Bangalore",
		"P.E.S. Institute of Technology, Bangalore",
		"R.V. College of Engineering, Bangalore",
		"RN Shetty Institute of Technology, bangalore",
		"RNSIT Institute of Technology, Bangalore",
		"Sapthagiri College of Engineering, Bangalore",
		"Sir M. Visvesvaraya Institute of Technology, Bangalore",
		"Sir M. Visvesvaraya Institute of Technology, Bangalore",
		"Sri Krishnadevaraya Education Trust, bangalore",
		"University Visvesvaraya College of Engineering, Bangalore",
		"Veterinary College, University of Agricultural Sciences, Bangalore",
		"Vijaya Composite Pre-University College, Bangalore",
		"American International University, Bangladesh",
		"Bapatla Engineering College, Bapatla",
		"College of Agricultural Engineering, Bapatla",
		"Sagar Institute of Technology & Management, Barabanki",
		"Invertis Institute Of Engineering And Technology, Bareilly",
		"Brij Bhushan Lal Public School, Bareilly",
		"Institute of Engineering and Technology, Rohilkhand Universit, Bareilly",
		"Shri Ram Murti Smarak College of Engineering & Technology, Bareilly",
		"Gujarat Flying Club, Baroda",
		"College of Engineering & Technology, Bathinda",
		"Giani Zail Singh College of Engineering & Technology,, Bathinda",
		"College of Engineering, Beed",
		"Mahatma Basaveshwar Education Society's College of Engineering, Beed",
		"Roland Institute of Tehcnology, Behrampur",
		"Rural Engineering College, Belgaum",
		"K.L.E.Society's College of Engineering and Technology, Belgaum",
		"Karnatak Law Society's Gogte Institute of Technology, Belgaum",
		"Vijayanagar Engineering College,, Bellary",
		"National Institute of science & technology, Berhampur",
		"National Institute of Science and Technology, Berhampur",
		"Institute of Engg. And Technology, Bhaddal",
		"Indian Institute of Carpet Technology, Bhadohi",
		"Dr.PAUL RAJ ENGINEERING COLLEGE, Bhadrachalam",
		"Bhagalpur College of Engineering, Bhagalpur",
		"Bihar Institute Of Silk & Textile, Bhagalpur",
		"Sri SVD Instt of Technology, Bharuch",
		"Anjuman Engineering College, Bhatkal",
		"Shantilal Shah Engineering College, Bhavnagar",
		"U V Patel College Of Engineering, Bhavnagar",
		"G D Rungta College of Engineering and Technology, Bhilai",
		"M.P.Christian College of Engineering and Technology, Bhilai",
		"Rungta College of Engineering & Technlogy, Bhilai",
		"Shri Shankaracharya College Of Engg. & Technology, Bhilai",
		"Shri Shankaracharya College Of Engg. & Technology, Bhilai",
		"Institute of Technology & Management, Bhilwara",
		"M.L.V. Textile Institute, Bhilwara",
		"SRKR Engineering college, Bhimavaram",
		"BRCM college of engineering & Technology, Bhiwani",
		"Technological Institute of Textiles and Sciences, Bhiwani",
		"Aurora's engineering college, Bhongiri",
		"AILASH CHANDRA BANSAL COLLEGE OF TECHNOLOGY, Bhopal",
		"Bansal College Of Engineering, Bhopal",
		"BHABHA ENGINEERING RESEARCH INSTITUTE, Bhopal",
		"Jai Narain College of Technology, Bhopal",
		"Laxmi Narain College of Technology, Bhopal",
		"Radha Raman Institute of Technology & Science, Bhopal",
		"SAGAR INSTITUTE OF RESEARCH AND TECHNOLOGY, Bhopal",
		"Swami Vivekananda College of Science and Technology, Bhopal",
		"All saints college of technology, Bhopal",
		"Bansal institute of science and technology, Bhopal",
		"Bhopal Engineering College, Bhopal",
		"Bhopal Inst of Tech and Science, Bhopal",
		"Government Engineering College, Bhopal",
		"Jai naraian college of technology, Bhopal",
		"Laxminarayan College of Technology, Bhopal",
		"Maulana Azad College of Technology, Bhopal",
		"NIT, Bhopal",
		"nri institute of information science&technology, Bhopal",
		"Oriental Institute of Science and Technology, Bhopal",
		"Patel College Of Science & Technology, Bhopal",
		"R.K.D.F. I.S.T., BHOPAL",
		"School of Information Technology , R.G.P.V., Bhopal",
		"Shree Institute of Science and Technology, Bhopal",
		"Technocrats institute of techonology, Bhopal",
		"Thakral college of technology, Bhopal",
		"Bhopal,Truba Institute of Engg. &

		<br/>Information Technology",
		"University institute of technology, Bhopal",
		"College Of Agricultural Engineering & Technology, Bhubanashewar",
		"NISER, Bhubaneshwar",
		"Trident Academy Of Technology, Bhubaneshwar",
		"Eastern Academy of Science and Technology, Bhubaneswar",
		"Gandhi Institute For Technology Advancement, Bhubaneswar",
		"IIIT, Bhubaneswar",
		"Mahavir Institute Of Engineering And Technology, Bhubaneswar",
		"Nalanda Institue of technology, Bhubaneswar",
		"The Techno School, Bhubaneswar",
		"College of Engineering and Technology, Bhubaneswar",
		"Institute of Technology Bhubaneswar, Bhubaneswar",
		"Kalinga Institute of Industrial Technology, Bhubaneswar",
		"Orissa Engineering College, Bhubaneswar",
		"Silicon Institute of Technology, Bhubaneswar",
		"Orissa Engineering College, Bhubneswar",
		"Government Engineering College, Bhuj",
		"INSTITUTE OF TECHNICAL EDUCATION AND RESEARCH, Bhuvaneswar",
		"Guru Nanak Dev Engineering College, Bidar",
		"S.V.E. Society's Rural Engineering College, Bidar",
		"BIT SINDRI, Bihar",
		"B.L.D.E. Association College of Engineering and Technology, Bijapur",
		"Malik Sandal Institute of Art and Architecture, Bijapur",
		"SECAB Institute Of Engineering and Technology, Bijapur",
		"Veera Engineering College, Bijnore",
		"Govt. Polytechnic College, Bikaner",
		"Engineering College, Bikaner",
		"Marudhar Engineering College, Bikaner",
		"Institute of Technology Guru Ghasidas University, Bilaspur",
		"Chouksey Engineering College, Bilaspur",
		"Government Engineering College, Bilaspur",
		"Fasuldades Associadas de S?o Paulo, Brazil",
		"PUC-RIO - Pontif?cia Universidade Cat?lica do Rio de Janeiro, Brazil",
		"Universidade Federal do Rio Grande do Norte, Brazil",
		"Politehnica University of Bucharest, Bucharest",
		"Babu Banarasidas Instt of Engg Tech & Research Centre, Bulandshahar",
		"Marathwada Institute of Technology, Bulandshahar",
		"Anuradha Engineering College, Buldana",
		"Padmabhushan Vasantraodada Patil Institute of Technology, Buldana",
		"Shri Sant Gajanan Maharaj College of Engineering, Buldana",
		"Bulgaria, Shoumen, High School of Natural Science and Mathematics",
		"Regional Engineering College, Burdwan",
		"College Of Leather Technology, Calcutta",
		"heritage institute of technology, Calcutta",
		"Nadia Institute Of Jute Technology, Calcutta",
		"Narula Institute of Technology, Calcutta",
		"NIT, Calicut",
		"University of Cambridge, Cambridge",
		"CHITKARA UNIVERSITY, Chandigarh",
		"National Institue of Pharmaceutical Education and Research, Chandigarh",
		"Chandigarh, University Institute Of Engineering and Technology, Panjab",
		"AMIET, Chandigarh",
		"Chandigarh college of engineering and technology, chandigarh",
		"Deptt.of Chemical engg. Panjab University, Chandigarh",
		"Punjab Engineering College, Chandigarh",
		"University Institute of Engineering and Technology, Panjab , Chandigarh",
		"College of Engineering, Chengannur",
		"The New College, Chennai",
		"B.S.A Crescent Engineering College, Chennai",
		"BHARATH INSTITUE OF SCIENCE AND TECHNOLOGY, Chennai",
		"D.G. Vaishnav College, Chennai",
		"GANESH INSTITUTE OF TECHNOLOGY, Chennai",
		"Institute for financial management and research, Chennai",
		"Jeppiaar engineering college, Chennai",
		"Jerusalem College Of Engineering, Chennai",
		"Loyola Institute of Business Administration, Chennai",
		"Sri Sai Ram Institute of Management Studies, Chennai",
		"SSN College of Engineering, Chennai",
		"Sthyabama University, Chennai",
		"Velammal Engineering College, Chennai",
		"A C College of Technology, Chennai",
		"Alagappa College of Technology, Chennai",
		"Anand Institute of higher technology, Chennai",
		"Bharath Institute Of Higher Education and Research, Chennai",
		"Chennai Institute of technology, Chennai",
		"Chennai Mathematical Institute, Chennai",
		"College of Engineering, Anna University, Chennai",
		"DMI College of engineering, Chennai",
		"DR MGR EDUCATIONAL AND RESEARCH INSTITUTE, CHENNAI",
		"Dr. MGR Engg. College, Chennai",
		"Hindustan College of engineering, chennai",
		"IIT, Chennai",
		"Institute Of Distance Education,University Of Madras, Chennai",
		"Jerusalem College of Engineering, Chennai",
		"KCG College of Technology, Chennai",
		"Krishna Engineering College, Chennai",
		"M.N.M. Jain Engg College, Chennai",
		"Madras Institute of Technology, Chennai",
		"Meenakshi Sundararajan Engineering College, Chennai",
		"NIST, Chennai",
		"Rajalakshmi Engineering College, Chennai",
		"Rajarajeswari Engineering College, Chennai",
		"Sathyabama institute of science and technology, Chennai",
		"saveetha engineering college, chennai",
		"Sree Sastha Institute of Engineering and Technology, Chennai",
		"Srinivasa Institute of Engineering and t, Chennai",
		"SRM INSTITUTE OF SCIENCE AND TECHNOLOGY, CHENNAI",
		"St. Joseph's College of Engineering, Chennai",
		"St. Peter's Engineering College, Chennai",
		"Vel Tech Engineering College at Avadi, Chennai",
		"Velammal Engineering College, Chennai",
		"St'Anns College, Chirala",
		"SJMIT, Chitradurga",
		"Institute of People's Science and Technology, Chitrakoot",
		"International Islamic University, Chittagong",
		"Cochin University of Science & Technology, Cochin",
		"Govt Model Engineering College, Cochin",
		"Sri Krishna College Of Engineering & Technology, Coimbatore",
		"Amrita School of Engineering, Coimbatore",
		"Coimbatore Institute of Technology, Coimbatore",
		"Government College of technology, Coimbatore",
		"Government College of Technology, Coimbatore",
		"Karunya Institute of Technology and Sciences, Coimbatore",
		"kumaraguru college of technology, Coimbatore",
		"Maharaja Engineering College, Coimbatore",
		"Nehru college of aeronautics & applied sciences, Coimbatore",
		"P.S.G. College of Technology, Coimbatore",
		"Park College of Engineering Technology, Coimbatore",
		"Sri Ramakrishana Engineering College, Coimbatore",
		"Sri Ramakrishna Engineering College, Coimbatore",
		"Tamil Nadu College of Engineering, Coimbatore",
		"V.L.B. Janaki Ammal College of Engineering and Technology, Coimbatore",
		"Bhubaneswar, College of Engineering",
		"Jagannath Institute of Engineering and Technology, Cuttack",
		"DRIEMS, Cuttack",
		"Institute of Technology, Dakshin Kannada",
		"C M Sc. College, Darbhanga",
		"Siliguri Institute of Technology, Darjeeling",
		"U B D T College of Engineering, Davanagere",
		"ICFAI University, Dehradun",
		"Tula's Institute, Dehradun",
		"University of Petroleum and Energy Studies, Dehradun",
		"Dehradun Institute of Technology, Dehradun",
		"Graphic Era Institute Of Technology, Dehradun",
		"University of Petroleum and Energy Studies, Dehradun",
		"Delhi, Faculty of Management Studies, University of Delhi",
		"IIIT, Delhi",
		"Indira Gandhi Institute of Technology, Delhi",
		"Maharaja Agrasen Institute of Technology, Delhi",
		"SRM UNIVERSITY, Delhi",
		"Amity School of Engineering & Technology, Delhi",
		"DCE, Delhi",
		"DOEACC(Department of Electronics Accrediated to Computer Courses, Delhi",
		"Guru Premsukh memorial college(ip university), Delhi",
		"GURU TEGH BAHADUR INST OF TECH,IP University, Delhi",
		"Hansraj College, Delhi",
		"IIT, Delhi",
		"Indian Society For technical Education, Delhi",
		"Indraprastha college for women, Delhi",
		"Institute of Engineers, Delhi",
		"Kirori Mal college - University enclave, Delhi",
		"NSIT (Netaji Subhash Instt. of Tech.), Delhi",
		"School Of planning & architecture, Delhi",
		"south campus, Delhi",
		"Sri Guru Tegh Bahadur Khalsa College, DU, Delhi",
		"St. Stephen's college, Delhi",
		"The Aeronautical Society of India, Delhi",
		"USIT, Delhi",
		"Vastu Kala Academy, School Of Architecture & interior designing, Delhi",
		"Birla Institute of Technology, Deoghar",
		"Bangladesh University of Engineering and Technology, Dhaka",
		"Notre Dame College, Dhaka",
		"Bokaro Institute of Technology, Dhanbad",
		"Indian School of Mines, Dhanbad",
		"Dharmapuri Dist.,Government Engineering College",
		"Sri DharmasthalaManjunatheshwara College of Engg & Tech., Dharwad",
		"SDM college of engineering and technolgy, Dharwar",
		"Dombivli (West),Jondhale College of Engineering",
		"Dev Sankriti College Of Technology, Durg",
		"MP Christian College of Engineering & Technology, Durg",
		"Bhilai Institute of Technology, Durg",
		"CSIT, Durg",
		"BENGAL COLLEGE OF ENGINEERING & TECHNOLOGY, Durgapur",
		"NIT, Durgapur",
		"kumaon engineering college, Dwarahat",
		"Krishna Murthy Institute of Technology and Engineering, Edulabad",
		"Sir C.R.R. College of Engineering, Eluru",
		"Model Engineering College,, Ernakulam",
		"Kongu Engineering College, Erode",
		"Institute of Road and Transport Technology,, Erode",
		"B.S.Anangpuria Institute of Tech. & Management, Faridabad",
		"Echelon Institute of Technology, Faridabad",
		"Lingaya's Institute of Management and Technology, Faridabad",
		"Y.M.C.A. Institute of Engineering, Faridabad",
		"Career Institute of Tech. and mgmt., Faridabad",
		"Tagone academy, Faridabad",
		"YMCA Institute of Engineering, Faridabad",
		"College of Engineering, Farmagudi",
		"Baba banda singh bahadur enginering college, Fatehgarh sahib",
		"Baba Banda Singh College of Engineering, Fatehgarh Sahib",
		"Shaheed Bhagat Singh College of Enginering and Technology, Ferozepur",
		"Dhirubhai Ambani Instt of Info & Comm Tech, Gandhinagar",
		"Government Engineering College, Gandhinagar",
		"FAU Erlangen-Nurnberg, Germany",
		"University of Ulm, Germany",
		"Dr. K.N. MODI INSTITUTE OF ENGINEERING AND TECHNOLOGY, Ghaziabad",
		"Ideal Institute of Technology, Ghaziabad",
		"Institute of Management Technolgy, Ghaziabad",
		"Lord Krishna College Of Engineerig, Ghaziabad",
		"R.D. Engineering College, Ghaziabad",
		"Sunderdeep Engineering College, Ghaziabad",
		"Vivekanand Institute of Technology and Sciences, Ghaziabad",
		",Ajay Kumar Garg Engineering College, Ghaziabad",
		"ABES ENGG COLLEGE, Ghaziabad",
		"ABES Engineering College, Ghaziabad",
		"B.B.I.T, Ghaziabad",
		"Ideal Institute Of Technology, Ghaziabad",
		"ims engineering college, Ghaziabad",
		"Inderprastha engg. college, Ghaziabad",
		"Krishna Engineering College, Ghaziabad",
		"Raj kumar goel institute of technology, Ghaziabad",
		"Shyama Prasad Institute of Technology and Management, Ghaziabad",
		"Shree Ganapathi Institute Of Technology, Ghaziabhad",
		"Krishna institute of engg. and tech, Ghiaziabad",
		"BITS - Pilani, Goa Campus",
		"National Institute of Construction management and Research (NICMA, Goa",
		"Goa College Of Enginering, Goa",
		"Acharya Narendra Dev College of Pharmacy, Gonda",
		"Madan Mohan Malviya Engeneering College, Gorakhpur",
		"SUYASH INSTITITE OF INFORMATION TECHNOLOGY, Gorakhpur",
		"Institute of Technology & Management, Gorakhpur",
		"Madan Mohan Malaviya Engineering College, Gorakhpur",
		"I.T.S. Engineering College, Greater Noida",
		"G.L. BAJAJ INST. OF TECH., Greater Noida",
		"Greater Noida, Hindustan Institute of Technology",
		"Greater Noida, Vishveshwarya Group of Instituions",
		"Vishveshwarya Institute of Engineering and Technology(V, Greater Noida",
		"APEEJAY Institute of Technology,School of Architecture a, Greater Noida",
		"College of Engineering & Technology, Greater Noida",
		"Galgotia's College of Engg. & Technology, Greater Noida",
		"IEC, College of Engineering & Technology,, Greater Noida",
		"IILM,A.H.L, GREATER NOIDA",
		"Noida Institute of Engg. & Technology, Greater Noida",
		"Skyline Institue of of Engineering & Technology,, Greater Noida",
		"Gudlavalleru Engineering college, Gudlavalleru",
		"G. H. PATEL COLLEGE OF ENGINEERING AND TECHNOLGY(GCET), Gujarat",
		"H.K.E. Society's Poojya Doddappa Appa College of Engineering,, Gulbarga",
		"Khaja Banda Nawaz College of Engineering, Gulbarga",
		"P.D.A. College of Engineering,, Gulbarga",
		"Jaypee Institute of engineering and technology, Guna",
		"R.V.R. and JCOP College of Engineering,, Guntur",
		"Tenali Engineering College, Guntur",
		"Koneru Lakshmaiah College of Engineering, Guntur",
		"Beant College of Engineering & Technology, Gurdaspur",
		"BM COLLEGE OF TECH & MGMT, GURGAON",
		"IILM Institute of Higher Education, Gurgaon",
		"Apeejay College Of Engineering, Gurgaon",
		"Dronacharya College of Engineering, Gurgaon",
		"Institute of Technology and Management, Gurgaon",
		"MDI, Gurgaon",
		"Assam Engineering College, Guwahati",
		"IIT, Guwahati",
		"Guru Kripa Campus, Gwalior",
		"Institute of Information Technology & Management, Gwalior",
		"IPS College Of Technology and Management, Gwalior",
		"Jiwaji University, Gwalior",
		"ABV-IIITM (Indian Instt of Information Tech and Mgmt), Gwalior",
		"Institute of Technology and Management, Gwalior",
		"Madhav Institute of Technology and Science,, Gwalior",
		"Maharana Pratap College of Technology,, Gwalior",
		"NRIITM, Gwalior",
		"Shriram college of engineering and management, Gwalior",
		"Haldia Insitute of Technology, Haldia",
		"NIT, Hamirpur",
		"Faculty of engg. and technology,gurukul kangri vishvavidyalaya, Hardwar",
		"Institute of Technology and Sciences, Haryana",
		"Bahubali College of Engineering, Hassan",
		"Malanad College of Engineering, Hassan",
		"College of Agricultural Engineering & Technology, Hissar",
		"Guru Jambheswar University, Hissar",
		"College of Textile Technology, Hooghly",
		"Adhiyamaan college of Engineering, Hosur",
		"Bengal Engineering College, Howrah",
		"K.L.E.Society's B.V. Bhoomraddi College of Engineering and Techn, Hubli",
		"BITS-Pilani, Hyderabad Campus",
		"DRK Institute of Science & Technology, Hyderabad",
		"Asifia college of engg. & technolgy, Hyderabad",
		"Avanthi Degree and PG College, Hyderabad",
		"Avanthi institute of Engg & Tech, Hyderabad",
		"Bharat Institute of Engineering and Technology, Hyderabad",
		"CMR College of Engineering and Technology, Hyderabad",
		"CVSR COLLEGE OF ENGINEERING, Hyderabad",
		"DVR COLLEGE OF ENGINEERING AND TECHNOLOGY, Hyderabad",
		"IIT, Hyderabad",
		"Nalla Malla Reddy Engineering College, Hyderabad",
		"Siva Sivani Institute of Management, Hyderabad",
		"TKR College Of Engineering And Technology, Hyderabad",
		"Vidya Jyothi Institute of Technolgy, Hyderabad",
		"Vignan Institute Of Technology and Science, Hyderabad",
		"Al Habeeb College Of Engineering and Technology, Hyderabad",
		"Ayaan collage of Engineering and Technology, Hyderabad",
		"C.M.R college of Engneering&Tech, Hyderabad",
		"Chaitanya bharathi institute of technology, Hyderabad",
		"College of Engineering, JNTU, Hyderabad",
		"CVR College of Engineering, Hyderabad",
		"Deccan College of Engineering and Technology, Hyderabad",
		"Deptt of Comp. Sc. and Engg.,Osmania University, Hyderabad",
		"G.Narayanamma Institute of Technology & Science (GNITS), Hyderabad",
		"Gokaraju rangaraju institute of engineering and technology, Hyderabad",
		"Guru Nanak Engineering College, Hyderabad",
		"ICFAI Institute of Science and Technology, Hyderabad",
		"IIIT (International Instt of Information Tech), Hyderabad",
		"INSTITUTE OF AERONAUTICAL ENGINEERING, Hyderabad",
		"JB Instituite of Engineering and Technology, Hyderabad",
		"Joginpally B R Engineering college, Hyderabad",
		"Mahatma gandhi institiute of technology, Hyderabad",
		"Maturi Venkata Subba Rao Engineering College, Hyderabad",
		"Muffakham Jah College of Engineering and Technology, Hyderabad",
		"Padmasri Dr. B V Raju Institute Of Technology, Hyderabad",
		"Pragati Maha Vidyalaya PG College, Hyderabad",
		"Sant samarth engineering college, Hyderabad",
		"School of Planning and Architecture, JNTU, Hyderabad",
		"Scient Institute of Engineering and Technology, Hyderabad",
		"Shadan College of Engineering and Technology, Hyderabad",
		"sree nidhi institute of science and technolog, Hyderabad",
		"Sridevi womens engg college, Hyderabad",
		"Swami Vivekananda Institute Of Technology, Hyderabad",
		"University College of Engineering, Osmania University, Hyderabad",
		"University Of Hyderabad, Hyderabad",
		"Vardhaman College Of Engineering, Hyderabad",
		"Vasavi College of Engineering, Hyderabad",
		"Vignana Jyothi Institute of Engineering and Technology, Hyderabad",
		"VNRVJIET, Hyderabad",
		"Indiana Institute of Technology, Indiana",
		"Parahyangan Catholic University, Indonesia",
		"Acropolis Institute of Technology and Research, Indore",
		"Lakshmi Narain College of Technology, Indore",
		"SGSITS, Indore",
		"Shri Raojibhai Gokulbhai Patel Gujarati Professional Institute, Indore",
		"Truba College of Engineering and Technology, Indore",
		"Aerospace and aviation academy, Indore",
		"Choithram School Indore, Indore",
		"DAVV (School of Computer Science ), Indore",
		"Devi Ahilya Vishwavidyalaya (Instt of Engg & Tech), Indore",
		"GSITS, Indore",
		"IES IPS Academy, Indore",
		"IIM, Indore",
		"Indore Institute of management Studies, Indore",
		"Indore Institute of Science and Technology, Indore",
		"Medicaps institute of technology and management, Indore",
		"Patel College of Science & Technology, Indore",
		"Rishiraj Institute of Technology, Indore",
		"Shri G.S. Institute of Technology and Science, Indore",
		"Shri Vaishnav Institute of Technology And Science, Indore",
		"Sthapatya Kala Bhawan Society, Indore",
		"NERIST, Itanagar",
		"Gyan Ganga College of Technology, Jabalpur",
		"GYAN GANGA INSTITUTE OF TECHNOLOGY & SCIENCES, Jabalpur",
		"Indian Institute of Information Technology Design and Manufa, Jabalpur",
		"Shri Ram Institute of Technology, Jabalpur",
		"Takshshila Institute of Engineering & Technology, Jabalpur",
		"Government Engineering College, Jabalpur",
		"Guru Ramdas Khalsa Institute of Science and Technology, Jabalpur",
		"Hitkarini college of engineering and technology, Jabalpur",
		"Haryana Engineering College, Jagadhri",
		"Government Engineering College, Jagdalpur",
		"Amity Institute of Engineering, Jaipur",
		"Amity School of Engineering, Jaipur",
		"Amity University, Jaipur",
		"Apex Institute of Engineering Technology, Jaipur",
		"Arya Institute Of Engineering And Technology, Jaipur",
		"C C S National Institute Of Agricultural Marketing, Jaipur",
		"Compucom Institute of Technology and Manangement, Jaipur",
		"Poornima College of Engineering, Jaipur",
		"Swami Keshwanad Institute of Technology Management & Gramothan, Jaipur",
		"Uma Nath Singh Institue Of Engineering & Technology, Jaipur",
		"Aayojan School of Architecture, Jaipur",
		"Arya College of Engineering & Information Technology, Jaipur",
		"Baldev Ram Mirdha Institute Of Technology,, Jaipur",
		"Global Instt of Technology, Jaipur",
		"Gyan Vihar Institute of Engineering & Technology, Jaipur",
		"Jagan nath institute of engineering & technology, Jaipur",
		"Jaipur Engineering College & Research Center, Jaipur",
		"Jaipur Engineering College,, Jaipur",
		"Kautilya Institute of Technology & Engineering,, Jaipur",
		"LNMIIT, Jaipur",
		"Maharshi Arvind Institute of Engineering & Tehcnology,, Jaipur",
		"Malaviya National Institute of Technology, Jaipur",
		"NIT, Jaipur",
		"Poornima College of Engineering, Jaipur",
		"Rai Foundation, Jaipur",
		"Rajasthan College of Engineering for Women,, Jaipur",
		"Rajasthan Institute of Engineering & Technology, Jaipur",
		"Rajiv Gandhi Memorial College of Aeronautics, Jaipur",
		"Regional College For Education Research & Technology,, Jaipur",
		"Sankara Institute of Technology,, Jaipur",
		"Seedling Academy of Design Technology & Management,, Jaipur",
		"Sri Balaji College of Engg. & Tech., Jaipur",
		"Sri Balaji College of Engineering & Technology,, Jaipur",
		"Stani Memorial College of Engineering & Technology, Jaipur",
		"Stani Memorial College of Engineering & Technology,, Jaipur",
		"Swami Keshawanand Instt of Tech & Mgmnt & Gramotthan,, Jaipur",
		"Lovely Professional University, Jalandhar",
		"Punjab Technical University, Jalandhar",
		"DAV Institute of Engineering & Technology, Jalandhar",
		"Dr. B R Ambedkar R.E.C., Jalandhar",
		"NIT Jalandhar, jalandhar",
		"J.T.Mahajan College of Engineering, Jalgaon",
		"Shrama Sadhna Trusts's College of Engineering and Technology, Jalgaon",
		"Jalpaiguri Government Engineering College, Jalpaiguri",
		"Shri Mata Vaishno Devi University, Jammu",
		"Government College of Engineering and Technology, Jammu",
		"XLRI, Jamshedpur",
		"Jamshedpur Women's College, Jamshedpur",
		"Loyola school, jamshedpur",
		"NIT, Jamshedpur",
		"Regional Institute of Technology, Jamshedpur",
		"Maharaja Surajmal Institute of Technology, Janakpuri",
		"Chitkara institute of engineering & tech, Jansla",
		"The University of Aizu, Japan",
		"G.T.Govt Polytechnic, Jatora",
		"U.N.S. Instituute of Engineering and Technology, jaunpur",
		"Institute of Engineering and Technology, Purvanchal University, Jaunpur",
		"Prasad Institute of Technology,, Jaunpur",
		"Government Engineering College, Jhalawar",
		"Bundelkhand Institute of Engineering and Technology, Jhansi",
		"INSTITIUTE OF ENGG. AND TECHNOLOGY BUNDELKHAND UNIVERSITY, Jhansi",
		"BIET, Jhansi",
		"College of Science and Engg., Jhansi",
		"Jhansi.,Bundelkhand Institute of Engineering & Technology,",
		"Usha Martin Academy, Jharkand",
		"Shekhawati Engineering College, Jhunjunu",
		"Aravali Institute Of Management, Jodhpur",
		"Engineering College & Research Center, Jodhpur",
		"Institute Of Engineering & Technology, Jodhpur",
		"M.B.M. Engineering College, Jodhpur",
		"National Law University, Jodhpur",
		"Jorhat Engineering College, Jorhat",
		"Mount Zion College of Engineering, Kadamannitta",
		"Haryana College of Technology and Management, Kaithal",
		"kiet engineering college, Kakainada",
		"JNTU College of Engineering, Kakinada",
		"Sri Sivasabramaniya Nadar College Of Engg., Kalavakkam",
		"JIS College of Engineering, Kalyani",
		"Govt. Engineering College, Kalyani",
		"Arulmigu Kalasalingam College of Engineering, Kamarajar",
		"Saveetha Engineering College, Kanchipuram",
		"Government College of Engineering, Kannur",
		"Ascent Institute of Management & Information Technology, Kanpur",
		"BHABHA COLLEGE OF ENGINEERING, Kanpur",
		"Bhabha Institute of Science and Technology, Kanpur",
		"Bhabha Institute of Technology, Kanpur",
		"Dr. Ambedkar Institute of Technology for Handicapped, Kanpur",
		"Dr. Gaur Hari Singhania Institute of Management & Research, Kanpur",
		"DR.AMBEDKAR INSTITUTE OF TECHNOLOGY FOR HANDICAPPED, Kanpur",
		"Harcourt Butler Technological Institute, Kanpur",
		"Krishna Girls Engineering College, Kanpur",
		"Krishna Institute of Technology, Kanpur",
		"Maharana Pratap Engineerin College, Kanpur",
		"NARAINA COLLEGE OF ENGINEERING AND TECHNOLOGY, KANPUR",
		"Pranveer Singh Institute of Technology, Kanpur",
		"RAMA Institute Of Engineering & Technology, Kanpur",
		"SHETH SHRINIWAS AGRAWAL INSTITUTE OF ENGINEERING & TECHNOLOGY, Kanpur",
		"University Institute Of Technology, Kanpur",
		"B.N.S.D.SIKSHA NIKETAN INTER COLLEGE, KANPUR",
		"C.S.J.M. Kanpur University, Kanpur",
		"Chandrashekhar Azad University Of Agriculture & Technology, Kanpur",
		"Dr. Virendra Swarup Education Centre, Kanpur",
		"HBTI, Kanpur",
		"IIT, Kanpur",
		"Kanpur Institute of Technology, Kanpur",
		"Maharana Pratap Engineering College, Kanpur",
		"Methodist high school, Kanpur",
		"Seth anandram jaipuria school, Kanpur",
		"Seth Anandram Jaipuria School, Kanpur",
		"Sir Padampat Singhania Education Centre, Kanpur",
		"C.S.I. Institute of Technology, Kanyakumari",
		"Noorulislam College of Engineering, Kanyakumari",
		"Government College of Enginerring, Karad",
		"Bharathiyar College Of Engineering & Technology, Karaikal",
		"A.C. College of Engineering and Technology, Karaikudi",
		"Central Electrochemical Research Institute, Karaikudi",
		"Mother Theressa college, Karimnagar",
		"University College of Engineering, Kariyavattom",
		"Doon Valley Institute Of Engineering & Technology, Karnal",
		"National Dairy Research Institute Dairy Science College, karnal",
		"V.S.B.Engineering College, Karur",
		"LBS College of Engineering, Kasargod",
		"SRM Institute of Management Studies, Kattankulathur",
		"Orissa School Of Mining Engineering Keonjhargarh, Keonjhar",
		"Sree Buddha College of Engineering, Kerala",
		"Vazir Sultan Engineering College, Khamman",
		"SN Govt. PG College,, Khandwa",
		"IIT, Kharagpur",
		"Shri U. V. Patel college of engineering, Kherva",
		"Mohamed Sathak Engineering College, Kilakarai",
		"Model Engineering College, Kochi",
		"School of Engineering,Cochin University of Science and Technolog, Kochi",
		"Kodaikanal Institute of Technolgy, Kodaikanal",
		"Kodaikanal Institute of Technology, Kodaikanal",
		"A.E. and C.S Pavan Engineering College, Kolar",
		"Bangalore College of Engineering and Technology, Kolar",
		"College of Architecture, Kolhapur",
		"D.Y.Patil College of Engineering and Technology, Kolhapur",
		"Dattajirao Kadam Tech. Education Society, Textile & Engg. Ins, Kolhapur",
		"Dr. J.J.Magdum College of Engineering, Kolhapur",
		"Kolhapur Institute of Technology College of Engineering, Kolhapur",
		"Tatyasahed Kore Institute of Engineering & Technology, Kolhapur",
		"Birbhum Institute Of Engineering, Kolkata",
		"Calcutta Institute Of Engineering And Management , Kolkata",
		"CAMELLIA SCHOOL OF ENGG & TECH., Kolkata",
		"Government College of Engineering and Ceramic Technology, Kolkata",
		"IISER, Kolkata",
		"Institute of Technology & Marine Engineering, Kolkata",
		"RCC Institute Of Information Technology, Kolkata",
		"SEACOM ENGINEERING COLLEGE, Kolkata",
		"St.Xaviers' College, Kolkata",
		"Techno India College of Technology, Kolkata",
		"Techno India Salt Lake, Kolkata",
		"Faculty of Engineering and Technology Jadavpur University, Kolkata",
		"IIIT, Kolkata",
		"IIM, Kolkata",
		"Indian Statistical Institute, Kolkata",
		"Institute of Jute Technology, Kolkata",
		"Jadavpur University, Kolkata",
		"Jadavpur University, Kolkata",
		"Marine Engineering Research Institute, Kolkata",
		"Meghnad Saha Institute of Technology, Kolkata",
		"school of information technology, Kolkata",
		"ST. THOMAS COLLEGE OF ENGINEERING & TECHNOLOGY, Kolkata",
		"University College Of Sciences & Technology, Kolkata",
		"mckv inst of engg, Kolkatta",
		"TKM College of Engineering, Kollam",
		"Seoul National University, Korea",
		"Pavol Jozef Safarik University, Kosice",
		"Gurukul College Of Engineering, Kota",
		"Engineering College Akelgarh, Kota",
		"Modi Institute of Technology, Kota",
		"Kothagudem School of Mines, Kothagudem",
		"MA College of Engineering, Kothamangalam",
		"National engineering college, Kovilpatti",
		"AWH Engineering College, Kozhikode",
		"IIM, Kozhikode",
		"NIT, Kozhikode",
		"West Bengal University of Animal and Fishery Scie, Krishi Vishwavidyala",
		"Government College of Engineering (Bergur), Krishnagiri",
		"Kalasalingam University, Krishnankoli",
		"G Pulla Reddy Engineering College, Kurnool",
		"NIT, Kurukshetra",
		"Regional Engineering College, Kurukshetra",
		"S.D.D.I.E.T. (Kurukshetra University), Kurukshetra",
		"University Science Instrumentation Centre Kurukshetra Univ, Kurukshetra",
		"Kuvempu University",
		"Modi Institute of Technology, Lakshmangarh",
		"College of Engineering Nilanga, Latur",
		"M.S. Bidve Engineering College, Latur",
		"Shyamlal College of Engineering Udgir, Latur",
		"Naval College of Engineering, Lonavla",
		"Dr. Babasaheb Ambedkar Technological University, Lonere",
		"Sant Longowal Institute of Engineering and Technology, Longowal",
		"PUNE UNIV.,PRAVARA RURAL ENGG. COLLEGE, LONI",
		"Amity Institute of Biotechnology, Lucknow",
		"Amity Institute of Information Technology, Lucknow",
		"Amity University, Lucknow",
		"Aryavart Institute Of Technology And Management, Lucknow",
		"BABU BANARSI DAS GROUP OF ENGG. COLLEGE., Lucknow",
		"Central Institute of Plastics Engineering and Technology, Lucknow",
		"College of Engineering Sciences & Technology, Lucknow",
		"Dr. M.C. Saxena Engineering and Technology, Lucknow",
		"INSTITUTE OF ENGINEERING AND TECHNOLOGY, Lucknow",
		"Institute Of Technology, Lucknow",
		"UPTEC, Lucknow",
		"Amity school of engineering, Lucknow",
		"Azad Institute of Engg. & Technology, Lucknow",
		"BBDNITM, Lucknow",
		"Government College of Architecture, Lucknow",
		"IET, Lucknow",
		"IIM, Lucknow",
		"Institute of Integral Technology, Lucknow",
		"INTEGRAL UNIVERSITY, Lucknow",
		"Mahanagar Boys, Lucknow",
		"Northern India Engg. College, Lucknow",
		"Saroj Institute of Technology & Management, Lucknow",
		"Sri Ram Swaroop Memorial College of Engg. & Management, Lucknow",
		"The Modern School, Lucknow",
		"College of Agriculture Engineering, Ludhiana",
		"Guru Nanakdev Engineering College, Ludhiana",
		"Sri Venkateshwara Hindu College of Engineering, Machilipatnam",
		"KLN COLLEGE OF ENGINEERING, Madurai",
		"Kamaraj University, Madurai",
		"Sethu Institute of Technology, Madurai",
		"Thiagarajar College of Engineering, Madurai",
		"Malout institute of management &information technology, Malout",
		"Punjab Institute Of Management And Technology, Mandi Gobindgarh",
		"Mandsaur Institute of Technology, Mandsaur",
		"P.E.S. College of Engineering, Mandya",
		",Manipal Institute of Technology, Manipal",
		"Dr. T.M.A. Pai Foundation, Manipal",
		"TA Pai Management Instiute, Manipal",
		"GLAITM, Mathura",
		"Sachdeva Institute of Technology, Mathura",
		"B.S.A. College of Engineering & Technology., Mathura",
		"G.L.A. Institute of Technology & Management, Mathura",
		"Hindustan College of Science & Technology, Mathura",
		"Rajeev Academy for Pharmacy, Mathura",
		"Sachdeva Institute of Technology, Mathura",
		"TKR COLLEGE OF ENGINEERING AND TECHNOLOGY, Medbowli",
		"Institue Of Technology And Management, Meerut",
		"J.P.Instutue Of Engineering And Technology, Meerut",
		"Kishan Institute Of Engineering And Technology, Meerut",
		"Radha Govind Engineering College, Meerut",
		"S.C.R.I.E.T Chaudhary Charan Singh University, Meerut",
		"Subharti University, Meerut",
		"Vidya College of Engineering, Meerut",
		"Bharat Institute of Technology, Meerut",
		"College of Engg. & Rural Technology, Meerut",
		"IIMT Engineering College, Meerut",
		"Meerut Institute of Engineering and Technology, Meerut",
		"Radha Govind Engineering College, Meerut",
		"Shobhit Institute of Engg. & Technology, Meerut",
		"Shri Gopichand College of Pharmacy, Meerut",
		"SAFFORNY INSTITUTE OF TECHNOLOGY CAMPUS, Mehsana",
		"C Abdul Hakeem College of Engineering Technology, Melvisharam",
		"BIT Patna Campus, Mesra",
		"B.I.T., Mesra",
		"Military College of Telecommunication Engineering, Mhow",
		"Michigan State University, Michigan",
		"Dr. K.N.Modi Institute of Pharmaceutical Science & Research, Modinagar",
		"Dr. Kedarnath Modi Institute of Engineering & Technology, Modinagar",
		"Abacus Institute of Engineering & Management, Mogra",
		"IISER, Mohali",
		"National Institute of Pharmaceutical Education and Research, Mohali",
		"Shaheed Udham Singh College Of Engineering and Technology, Mohali",
		"College of Engineering & Technology, Moradabad",
		"Institute of Foreign Trade & Management, Moradabad",
		"Moradabad Institute of Technology, Moradabad",
		"Lukhdhirji engg.college, Morbi",
		"L.E. College, Morvi (Gujarat), Morvi",
		"MOTIHARI COLLEGE OF ENGINEERING, MOTIHARI",
		"Bhavan's SPJIMR, Mumbai",
		"Jamnalal Bajaj Institute of Management Studies, Mumbai",
		"Rajiv Gandhi Institute of Technology, Mumbai",
		"Rizvi Institute of Management Studies and Research, Mumbai",
		"Tata Institute of Social Sciences, Mumbai",
		"A.C.PATIL College of Engg., Mumbai",
		"Anjuman-I-Islam's S.M.H. Saboo Siddik College of Engineering, Mumbai",
		"Bharatiya Vidya Bhavan's Sardar Patel College of Engineering, Mumbai",
		"Bharatiya Vidya Bhavan's Sardar Patel College of Engineering,, Mumbai",
		"D.J.Sanghvi College of engineering, Mumbai",
		"Datta Meghe College of Engineering, Mumbai",
		"Department of Chemical Technology, Mumbai",
		"Don Bosco Institute of Technology, Mumbai",
		"FR Conceicao Rodrigues College of Engineering, Mumbai",
		"FR Conceicao Rodrigues College of Engineering, Mumbai",
		"Hiranandani Foundation's Institute of Technology, Mumbai",
		"Hiranandani Foundation's Institute of Technology, Mumbai",
		"IIT, Mumbai",
		"Indian Education Society's College of Architecture, Mumbai",
		"Institute. Of Technology Sindhi Society, Mumbai",
		"Jamnalal Bajaj Institute of Management Studies, Mumbai",
		"k j somaiya institute of engineering and information technology, Mumbai",
		"K.J. Somiya College of Engineering, Mumbai",
		"K.J. Somiya College of Engineering, Mumbai",
		"Kamla Raheja Vidhyandhi Instt for Architecture and Env. Studies, Mumbai",
		"Kirti college, Mumbai",
		"L&T, Mumbai",
		"Late Bhausaheb Hiray S.S. Trust's College of Architecture, Mumbai",
		"M.E.T., Mumbai",
		"M.H. Saboo dik College of Engineering, Mumbai",
		"M.H. Saboo Siddik College of Engineering, Mumbai",
		"Narsee Monjee Institute Of Management and Higher Studies, Mumbai",
		"National Institute Of Industrial Engg., Mumbai",
		"Padmabhusan Vasantdada Patil Pratishthan's College of Engineeri, Mumbai",
		"Ramrao Adik Institute of Technology, Mumbai",
		"Rizvi College of Architecture,, Mumbai",
		"Shah and Anchor Kutchhi Engineering College, Mumbai",
		"Sir J.J. College of Architecture, Mumbai",
		"St.Xaviers Technical Institute, Mumbai",
		"Thadomal Shahani Engg. College, Mumbai",
		"Vidyalankar Institute of Technology, Mumbai",
		"Vivekanand Education Society, Instt of Technology, Mumbai",
		"VJTI, Mumbai",
		"Watumal Institute of Electronics Engineering, Mumbai",
		"DEENBANDHU CHHOTU RAM UNIVERSITY OF SC.& TECHNOLOGY, Murthal",
		"New Engineering College, Murthal",
		"S.D. College of Engineering and Technology, Muzaffarnagar",
		"Muzaffarpur Institute of Technology, Muzaffarpur",
		"Lakireddy balireddy college of engineering, Mylavaram",
		"National Institute of Engineering, Mysore",
		"Office:- Geeta Shishu Shikshana Sangha Campus,Siddartha Nagar, Mysore",
		"Sri Jayacharmarajendra College of Engineering,, Mysore",
		"NA, NA",
		"Department Of Agricultural Engg.,Bidhan Chandra Krishi Viswavidy, Nadia",
		"Dharmsinh Desai Institute of Technology, Nadiad",
		"G.H.Raisoni College Of Engineering, Nagpur",
		"G.S.College of Commerce and Economics, DMSR, Nagpur",
		"Gurunanak Institute of Engineering and Technology, Nagpur",
		"Institute Of Management Technology, Nagpur",
		"KDK College of Engineering, Nagpur",
		"National Power Training Institute, Nagpur",
		"Priyadarshini Institute Of Engineering & Technology, Nagpur",
		"St. Vincent Pallotti College of Engineering & Technology, Nagpur",
		"G. H. Raisoni Polytechnic, Nagpur",
		"K.D.K. College of Engineering, Nagpur",
		"Kavikuguru Instt of Tech. and Sc., Nagpur",
		"Laxminarayan Institute of Technology,, Nagpur",
		"Ministry of Home Affairs National Fire Service College, Nagpur",
		"NIT, Nagpur",
		"Priyadashini College of Engineering and Architecture, Nagpur",
		"Ramdeo Baba Kamla Nehru College, Nagpur",
		"RKNEC, Nagpur",
		"Shri Ramdeo baba kamla nehru engineering college, nagpur",
		"Shri Ramdeobaba Kamla Nehru Engineering College, Nagpur",
		"Visvesvaraya National Institute Of Technology, Nagpur",
		"Yeshwantrao chavam collehe of engg, Nagpur",
		"Yeshwantrao Chavan College of Engineering, Nagpur",
		"Birla Institute of Applied Sciences ,, Nainital",
		"Mona College of Engineering and Tech., Nalgoda",
		"k.s.rangasamy college of technology, namakkal",
		"paavai engineering college, namakkal",
		"Arulmigu Meenakshi Amman College of Engineering, Namandi",
		"M G M College of Engineering, Nanded",
		"Shri Guru Gobind Singhji College of Engineering & Technology, Nanded",
		"Rajeev Gandhi Memorial College Of Engg. and Technology, Nandyal",
		"JSPM, Nashik",
		"N.D.M.V.P. Samaj's College of Architecture, Nashik",
		"K.K. Wagh College of Engineering, Nasik",
		"ITM (Institute for Technology and Management), Navi Mumbai",
		"Annasaheb Chudaman Patil College of Engineering, Navi Mumbai",
		"Bharati Vidyapeeth's College of Engineering,, Navi Mumbai",
		"Datta Meghe College of Engineering, Navi Mumbai",
		"Datta Meghe College of Engineering, Navi Mumbai",
		"FR Conceicao Rodrigues Institute of Technology, Navi Mumbai",
		"FR Conceicao Rodrigues Institute of Technology, Navi Mumbai",
		"Indira Gandhi College of Engineering, Navi Mumbai",
		"Lokmanya Tilak College of Engineering, Navi Mumbai",
		"Lokmanya Tilak College of Engineering, Navi Mumbai",
		"Mahatma Gandhi Mission's College of Engineering, Navi Mumbai",
		"Manjara Charitable Trust's College of Engineering, Navi Mumbai",
		"Pillais' College of Architecture, Navi Mumbai",
		"Rajiv Gandhi Institute of Technology, Navi Mumbai",
		"Ramrao Adik Institute of Technology, Navi Mumbai",
		"Terna Engineering College, Navi Mumbai",
		"Quba Educational Society Engineering College, Nellore",
		"Netarhat avasiya vidyalay, Netarhat",
		"University of Twente, Netherlands",
		"Bharati Vidya Peeth's College Of Engineering, New Delhi",
		"New Delhi, Delhi Insititute Of Advacned Studies",
		"G.B.Pant Govt. Engineering College, New Delhi",
		"New Delhi, Indian Institute of Foreign Trade",
		"Bharti VidyaPeeth's College of Engineering, New Delhi",
		"Department of Computer Science University of Delhi, New Delhi",
		"DPS RK Puram, New Delhi",
		"F/o Engg. & Tech. , Jamia Millia Islamia, New Delhi",
		"IGNOU, New Delhi",
		"Jawahar Lal Nehru University, New Delhi",
		"Sri venkatesvara college,DU, New Delhi",
		"The Institution of Electronics & telecommunication Engineers, New Delhi",
		"Nagpur Yuwak Sikshan Sanstha's College of Engineering, New Mumbai",
		"International Management Institute., Newdelhi",
		"Northern India Engineering College, Newdelhi",
		"North Eastern Regional Institute of Science and Technology, Nirjuli",
		"Amity Business School, Noida",
		"Amity institute of information technology, Noida",
		"Amity University, Noida",
		"FDDI, Noida",
		"Greater Noida Institute of Technology, Noida",
		"JSSATE, Noida",
		"Sharda University, Noida",
		"United college of Engineering & Research , Noida",
		"Amity school of engineering, Noida",
		"CDAC, Noida",
		"IEC College of Engineering and Technology, Noida",
		"J.S.S. Academy of Technical Education, Noida",
		"Jaypee Institute of Information and Technology, Noida",
		"Mahatma Gandhi Mission College of Engg. & Technology, Noida",
		"Priyadarshani College of Computer Sciences, Noida",
		"Ram Eesh Institute of Vocational and Technical Education, Noida",
		"Vishwa Bharati Public School, Noida",
		"Noida.,Greater Noida Institute of Technology",
		"Sri Sarathi Institute of Engineering and Technology, Nuzvid",
		"Golden Valley Institute of Technology, Oorgaum",
		"College of Engineering, Osmanabad",
		"Shree Tuljabhavani College of Engineering, Osmanabad",
		"Terna Public Charitable Trust, Colllege of Engineering, Osmanabad",
		"Other",
		"Goa College of Architecture, Panaji",
		"College Of Engg., Pandharpur",
		"APIIT SD INDIA, Panipat",
		"Asia Pacific Institute Of Innformation And Technology SD In, Panipat",
		"N.C. College of Engineering, Israna, Panipat",
		"College of Technology GB Pant University of Agriculture & Te, Pantnagar",
		"College of Agriculture Technology, Parbhani",
		"Ecole Polytechnique of Paris, Paris",
		"TRR College Of Engineering, Inole, Patancheru",
		"Punjabi University, Patiala",
		",Mohindra college, Patiala",
		"Department Of Computer Science & Applications,Punjabi Univers, Patiala",
		"Department of Computer Science and Applications, Punjab Univer, Patiala",
		"Department of Computer Science and Engineering, Punjab Univers, Patiala",
		"Engineering College, Patiala",
		"Thapar Institute Of Engineering & Technology, Patiala",
		"Birla Institute Of Technology, Patna",
		"IIT, Patna",
		"NIT, Patna",
		"R.P. Sharma Institute of Technology, Patna",
		"Bihar College Of Engineering ,Patna University, Patna",
		"Maulana Azad College Of Engineering & Technology, Patna",
		"Patna Science College, Patna",
		"Sanjay Gandhi Instt Of Dairy Tech,Rajendra Agricultural Univ, Patna",
		"Sree Buddha College of Engineering, Pattor",
		"Pauri Garhwal, Govind Ballabh Pant Engineering College",
		"Pauri-Garhwal,Govind Ballabh Pant Engineering College",
		"Institute of Road and Transport Technology, Periyar Distt",
		"Erode Sengunthar Engineering College, Periyar",
		"Kongu Engineering College, Perundurai",
		"Ramgarhia Institute of Engineering & Techology, Phagwara",
		"BITS, Pilani",
		"2 LO in Olsztyn, Poland",
		"High School in Cracow, Poland",
		"Liceum #171, Poland",
		"University of Adam Mickiewicz, Poland",
		"Pondicherry Engineering College, Pondicherry",
		"V.R.S. and Y.R.N. College of Technology, Department of Oil Te, Prakasam",
		"Sudharsan Engineering college, Pudukkottai",
		"Mookambigai college of engg., Pudukottai",
		"IISER, Pune",
		"International School of Business & Media, Pune",
		"M.E.S. College Of Engineering, Pune",
		"MIT College of Engineering, Pune",
		"Sinhgad Academy of Engineering, Pune",
		"Sinhgad Institute Of Management, Pune",
		"Symbiosis Center for Management and Human Resource Development, Pune",
		"Symbiosis Institute of International Business, Pune",
		"Symbiosis Institute of Management Studies, Pune",
		"Symbiosis Institute of Technology, Pune",
		"Vishwakarma Creative-i College, Pune",
		"All India Shri Shivaji Memorial Society's College of Engineering,, Pune",
		"Army Institute of Technology, Pune",
		"B.K.P. Sabha's College of Architecture, Pune",
		"Bharati Vidyapeeth's College of Engineering, Pune",
		"Bharati Vidyapeeth's College of Engineering,, Pune",
		"College of Engineering, Pune",
		"College of Military Engineering, Pune",
		"College of Science, Pune",
		"Cummins College of Engineering for Women, Pune",
		"Cusrow Wadia Institute of Technology, Pune",
		"Cusrow Wadia Institute of Technology, Pune",
		"D.Y. Patil College of Engineering, Pune",
		"Dr D Y Patil College of Engineering, Pune",
		"Dr. Bhanuben Nanavati College of Architecture for Women, Karve Na, Pune",
		"Dr. DYPatil Pratisthan?s College of Engineering for Women, Pune",
		"Engineering, Pune",
		"G S MOZE COLLEGE OF ENGG., Pune",
		"Government College of Engineering, Pune",
		"IMCC, Pune",
		"Institute for Aeronautical Engineering & Information Technology, Pune",
		"Institute of business Management &Research, chinchwad, Pune",
		"Institute of Science, B.C.S. Science College, Pune",
		"Maharashtra Academy Of Engineering, Pune",
		"Maharashtra Institute of Technology, Pune",
		"Marathwada Mitra Mandal's College of Architecture, Pune",
		"P.V.G.s College of Engineering and Technology-Vidyanagar, Pune",
		"Pune Institute of Computer Technology, Pune",
		"Pune Institute of Computer Technology- Dhankawadi, Pune",
		"Pune Vidyarthi Griha's College of Engineering and Technology, Pune",
		"Rajarshi shahu college of engineering, Pune",
		"S.V.P. Mandal's College of Engineering, Pune",
		"s.v.p.m college of engineering,malegaon(b.k)baramati, pune",
		"Sinhgad College of Engineering, Pune",
		"Symbiosis Institute of Telecom Management, Pune",
		"Vidya Pratisthan's College of Engineering, Pune",
		"Vishwakarma Institute of Technology, Pune",
		"IITT College of Engineering, Punjab",
		"J.S.P. Mandal's B.N. College of Engineering, Pusad",
		"Rajiv Gandhi Institute of Petroleum Technology (RGIPT), Rae Bareli",
		"Feroze Gandhi Institute of Engg. & Technology, Raebareli",
		"College of Agricultural Engineering, Raichur",
		"S.L.N. College of Engineering, Raichur",
		"O.P.Jindal Institute of Technology , Raigarh",
		"Dr. Babasaheb Ambedkar Technological University, Raigarh",
		"Konkan Education Society's Engineering College, Raigarh",
		"Konkan Gyanpeeth Santha's College of Engineering, Raigarh",
		"Central College of Engineering and Management, Raipur",
		"Disha Institue Of Management And Technology, Raipur",
		"Disha Institute Of Management And Tehcnology, Raipur",
		"NIT, Raipur",
		"Vindhya Institute of Technology And Science, Raipur",
		"College of Dairy Technology, Raipur",
		"Engineering College, Raipur",
		"Raipur Institute of Technology, Raipur",
		"SSCET, Raipur",
		"Shri Rawatpura Sarkar Institute Of Technology, Raipus",
		"R.K.D.F. Institute of Science and Technology, Raisen",
		"Banasthali University, Rajasthan",
		"IIT, Rajasthan",
		"Chitkara Institute of Engineering and Technology, Rajpura",
		"Ghousia College of Engineering, Ramanagaram",
		"Usha Martin College, Ranchi",
		"Birla Institute of Technology, Ranchi",
		"National Institute of Foundry and Forge, Ranchi",
		"S.T.J. Institute of Technology, Ranebennur",
		"Rajaram Shinde College of Engineering, Ratnagiri",
		"Institute Of Advanced Computer And Research Engineering Coll, Rauagada",
		"GANDHI INSTITUTE OF ENGINEERING AND TECHNOLOGY, Rayagada",
		"Majhigharini Institute of Technology & Science, Rayagada",
		"R.M.K. Engineering College, Redhills",
		"University of Latvia, Physics and Mathematics facul, Republic of Latvia",
		"Government Engineering College, Rewa",
		"Vaish College of Engineering, Rohtak",
		",Babes-Bolyai University, Romania",
		"National College Tudor Vianu, Romania",
		"University of Bucharest, Romania",
		"College of Engineering Roorkee, Roorkee",
		"IIT, Roorkee",
		"Rayat Institute of Engineering & Information Technology , Ropar",
		"Bhai Jaitaji College of Engineering & Technology Chamkour Sahib, Ropar",
		"I.E.T BHADDAL, Ropar",
		"IET, Ropar",
		"NIT, Rourkela",
		"Regional Engineering College, Rourkela",
		"SETH VISHAMBHARNATH INST. OF ENG.RESEARCH &TECHNOLOGY, Safedabad",
		"Government Engineering College, Sagar",
		"Indira Gandhi Government Engineering College, Sagar",
		"Shobhit Institute of Engg. & Technology, Saharanpur",
		"Annai Mathammal Sheela Engineering College, Salem",
		"Government College of Engineering, Salem",
		"Government College of Engineering, Salem",
		"K.S. Rangasamy College of Technology, Salem",
		"Mahendra Engineering College, Salem",
		"Sona College of Technology, salem",
		"Vinayaka Mission's Kirupanada Variyar Engineering College, Salem",
		"College of Agricultural Engg, Rajendra Agricultural Univ, Samastipur",
		"University College of Engineering Burla, Sambalpur",
		"Amritvahini College of Engineering, Sangamner SK",
		"Appasaheb Birnale College of Architecture, Sangli",
		"K.E.Society's College of Engineering, Sangli",
		"Walchand College of Engg, Sangli",
		"SHANMUGHA ARTS ACIENCE TECHNOLOGY AND RESEARCH ACADEMY, SASTRA",
		"Karmaveer Bhaurao Patil College of Engineering & Polytechinc, Satara",
		"Bannari Amman Institute of Technology, Sathyamangalam",
		"SBS Nagar, Rayat Institute of Engineering and IT",
		"Institute of Aeronautical Engineering, Secunderabad",
		"Sri satya sai institute of science and technology , Sehore",
		"P.R.R.M Engineering College, Shabad",
		"Shri Sant Gajanan Maharaj College of Engineering, Shegaon",
		"Bengal Engineering and Science University, Shibpur",
		"IITT College of engineering Kala Amb, Shimla",
		"Jawaharlal Nehru National College of Engineering, Shimoga",
		"St. mary's junior colege, Shirva",
		"Syed hashim college of engineering, Siddipet",
		"Sobhasaria Engineering College, Sikar",
		"NIT, Silchur",
		"Regional Engineering College, Silchur",
		"Birsa Institute of Technology, Sindri",
		"Nanyang Technological University, Singapore",
		"IITT College of Engineering, Sirmour",
		"Institue of Engineering and Technology, Sitapur",
		"Mepco Schlenk Engg College, Sivakasi",
		"Comenius University, Slovakia",
		"Chitkara University, Solan",
		"JAYPEE UNIVERSITY OF INFORMATION TECHNOLOGY, Solan",
		"Brahmdevdada Mane Institute of Technology, Solapur",
		"Walchand Institute of Technology, Solapur",
		"Future Institute of Engineering & Management , Sonarpur",
		"Chhotu Ram State College of Engineering, Sonepat",
		"Hindu Institute. of Engg., Sonipat",
		"Sistam college of engineering, Srikakulam",
		"National Institute of Technology, Srinagar",
		"NIT, Srinagar",
		"Regional Engineering College, Srinagar",
		"Karnataka Regional Engineering College, Srinivasnagar",
		"Sri Venkateswara College of Engineering, Sriperumbudur",
		"MOOKAMBIGAI COLLEGE OF ENGINEERING, Srivasanagar",
		"Kurunji Venkatramana Gowda College of Engineering, Sullia",
		"Kamla Nehru Institute of Technology, Sultanpur",
		"Rajarshi Rananjay Sinh Instute of Management & Technology, Sultanpur",
		"Kamla Nehru Institute of Technology, Sultanpur",
		"Sri Sai Aditya Institute of Science & Technology, Surampalem",
		"pragati engineering college, Surampalem",
		"C.K Pithawal College of Engg & Tech, Surat",
		"NIT, Surat",
		"Regional Engineering College, Surat",
		"Sardar Vallabhbhai Regional College of Engineering & Technology, Surat",
		"Sarvjanik College of Engineering and Technology, Surat",
		"C U Shah College of engineering & Technology, Surendranagar",
		"NIT, Surtakal",
		"Sri Venkateshwara Engineering College, Suryapet",
		"Parshwanath Charitable Trust's College of Engineering, Thane",
		"Shivajirao's Jondhale College of Engineering, Thane",
		"Vidyavardhini's College of Engineering and Technology, Thane",
		"Periyar Maniammai College of Technology for Women, Thanjavur",
		"S.A.S.T.R.A., Thanjavur",
		"Shanmugha College of Engineering, Thanjavur",
		"Jaya Engineering College, Thiruninravur",
		"College Of Engineering, Thiruvananthapuram",
		"College of Engineering, Thiruvananthapuram",
		",SCT College of Engineering, Thiruvanathapuram",
		"Arunai Engineering College, Thiruvannamali",
		"Dr. Navalar Nedunchezhiyan College of Engineering, Tholudur",
		"Government Engineering College, Thrissur",
		"Kalpataru Institute of Technology, Tiptur",
		"Shivanthi Aditanar College of Engineering,, Tiruchendur",
		"K.S.Rangasamy College of Technology, Tiruchengode",
		"Angala Amman College of Engineering and Technology, Tiruchirapalli",
		"Bharathidasan Institute of Engineering and Technology, Tiruchirapalli",
		"College of Agricultural Engineering, Tiruchirapalli",
		"J.J. College of Engineering and Technology, Tiruchirapalli",
		"Jayaram College of Engineering and Technology, Tiruchirapalli",
		"Mookambigai College Of Engineering, Tiruchirapalli",
		"NIT, Tiruchirapalli",
		"Regional Engineering College, Tiruchirapalli",
		"Bharathidasan Institute of Engineering and Technology, Tiruchiraplli",
		"M.I.E.T Engineering College,, Tiruchirappalli",
		"Manonmaniam sundranar university, Tirunelveli",
		"Government College of Engineering, Tirunelveli",
		"Government College of Engineering, Tirunelveli",
		"Indian Engineering College, Tirunelveli",
		"PSN college of engineering and technology, Tirunelveli",
		"Tirupati SREE VIDYANIKETHAN ENGINEERING COLLEGE",
		"Tirupati SREE VIDYANIKETHAN ENGINEERING COLLEGE",
		"Sree Vidyanikethan Engineering College, Tirupati",
		"Sree Vidyanikethan Engineering College, Tirupati",
		"Sri Venkateswara University College of Engineering, Tirupati",
		"Sri Ram Engineering College, Tiruvallur Taluk",
		"TamilNadu University, Tmail Nadu",
		"Bharathidasan Institute of Management, Trichy",
		"Bharadhidasan University, Trichy",
		"Jayaram College of Engineering and Technology, Trichy",
		"LOURDES MATHA COLLEGE OS SCIENCE AND TECHNOLOGY, Trivandram",
		"Government College of Engineering, Trivandrum",
		"Bhabha Atomic Research Centre, Trombay",
		"Siddaganga Institute of Technology, Tumkur",
		"College of Technology and Engineering, Udaipur",
		"Maharana Pratap University of Agriculture and Technology, Udaipur",
		"College of Dairy Science, Udaipur",
		"College of Technology and Agricultural Engineering, Udaipur",
		"Geetanjali Institute Of Technical Studies, Udaipur",
		"Mody College of Engineering & Technology, Udaipur",
		"Shrinathji Institute Of Technology And Engg., Udaipur",
		"Merit-IIT, Udhgamandalam",
		"NMAN Institute of Technology, Udupi",
		"ALPINE INSTITUTE OF TECHNOLOGY, Ujjain",
		"Mahakal Institute of Technology and Science, Ujjain",
		"Governemnt Engineering College, Ujjain",
		"Mahakal Institute of Technology, Ujjain",
		"V.R.S. College of Engineering and Technology, Ulundurpet",
		"University of Roorkee, Uttaranchal",
		"ISTAR, v v nagar",
		"Vignan\'s engineering college, vadlamudi",
		"Parul Institute of Engineering & Technology, Vadodara",
		"Sigma Institute of Technology & Engineering, Vadodara",
		"Faculty of Technology and Engineering, Vadodara",
		"Birla Vishvakarma Mahavidyalaya, Vallabh Vidyanagar",
		"DC Patel School of Architecture, Vallabh Vidyanagar",
		"Priyadarshini Engineering College, Vaniyambadi",
		"Institute of Technology, Banaras Hindu University, Varanasi",
		"Mahatma Gandhi Kashi Vidyapith, Varanasi",
		"St.Johns, Varanasi",
		"Sunbean English School Bahgwanpur, Varanasi",
		"sardar vallabhai patel insti. of tech., Vasad",
		"ADHIPARASAKTHI COLLEGE OF ENGG, Vellore",
		"Thanthai Periyar Government Institute of Technology, Vellore",
		"Vellore Engineering College, Vellore",
		"vellore institute of technology, vellore",
		"S.A.T.I, Vidisha",
		"Samrat Ashok Technological Institute, Vidisha",
		"N.B.K.R. Institute of Science and Technology, Vidyanagar",
		"Hanoi-amsterdam, Vietnam, Hanoi",
		"Dai Hoc Su Pham Hanoi, Vietnam",
		"K L University, Vijayawada",
		"koneru lakshmaiah college of engineering, Vijayawada",
		"P.V.P Siddhartha Institue of Technology, vijayawada",
		"Velagapudi Ramakrishna Siddhartha Engineering College, Vijayawada",
		"Chaitanya Engineering College, Visakhapatnam",
		"GAYATRI VIDYA PARISHAD COLLEGE OF ENGINEERING FOR WOMEN, Visakhapatnam",
		"PYDAH COLLEGE OF ENGINEERING AND TECHNOLOGY, Visakhapatnam",
		"Andhra university college of engg., Visakhapatnam",
		"College of Engineering, Visakhapatnam",
		"G V P College of Engineering, Visakhapatnam",
		"Gandhi Institute of Technology and Management, Visakhapatnam",
		"Raghu engineering college, Visakhapatnam",
		"Raghu Institute of Technology, Vishakhapatnam",
		"Andhra University Engineering College, Vishakhapatnam",
		"Anil Neerukonda Inst of Tech & Sciences, Vishakhapatnam",
		"Gandhi Instt of Tech and Mgmt (College of Engg), Vishakhapatnam",
		"VIIT, Vizag",
		"AVANTHI INSTITUTE OF ENGINEERING AND TECHNOLOGY, VIZIANAGARAM",
		"St.Theressa Institute of engineering and technolgy, Vizianagaram",
		"mvgr college of engineering, vizianagaram",
		"MVGR College Of Engineering,, Vizianagaram",
		"Masterji Degree & P.G College, Warangal",
		"S.R.Engineering College, Warangal",
		"Kakatiya Institute of Technology and Science, Warangal",
		"Kakatiya Institute of Technology and Science, Warangal",
		"NIT, Warangal",
		"Regional Engineering College,Warangal, Warangal",
		"S.R.K.R. Engineering College, Warangal",
		"Sir C.R. Reddy College of Engineering, Warangal",
		"Bapurao Deshmukh College of Engineering, Wardha",
		"Seth Jai Parkash Mukand Lal Instt of Engg and Tech, Yamuna Nagar",
		"Regency Institute of Technlogy, Yanam",
		"Darda Engineering College, Yavatmal",
		"Jawahar Lal Darda Institute of Engineering, Yavatmal",
		"Jawaharlal Darda Institute of Engineering & Technology MIDC, Yavatmal",
		"Government Residential Women's Polytechnic, Yeotmal",
		"Arkay College of Engineering and Technology, Zaheerabad",
		"Indus Institute of Technology & Engineering, Ahmedabad",
		"Allahabad united college of engineering and research, Allahabad",
		"LAXMI DEVI INSTITUTE OF ENGINEERING AND TECHNOLOGY, ALWAR",
		"siddhi vi-nayak college of science & higher education, Alwar",
		"Rajarshi Rananjay Sinh Institute Of Management & Technology, Amethi",
		"SETH VISHAMBHAR NATH INSTITUTE OF ENGENEERING RESEARCH AND , Barabanki",
		"Rungta college of engineering, Bhilai",
		"SHRI SHANKARACHARYA COLLEGE OF ENGG. & TECH, Bhilai",
		"Vizianagaram, Miracle Educational Society Group Of Institut, Bhogapuram",
		"barkatullah university institute of technology, Bhopal",
		"Kalinga Institute Of Industrial Technology(KIIT), Bhubaneswar",
		"Bhubneshwar odisha kalinga institute of technology, Bhubaneswar",
		"Sambalpur, VEER SURENDRA SAI UNIVERSITY OF TECHNOLOGY, Burla",
		"Rayapati Venkata Ranga Rao & Jagarlamudi Chandramou, Chandramoulipuram",
		"Easwari Engineering College, Chennai",
		"Sri Sairam Engineering College, Chennai",
		"Chilakapalem jn.srikaulam dist., SRI SIVANI COLLEGE OF ENGINEERING",
		"RVR&JC COLLEGE OF ENGINEERING, Chowdavaram, Guntur Dist",
		"HINDUSTHAN COLLEGE OF ENGINEERING AND TECHNOLOGY, COIMBATORE",
		"SSK College of Engineering & Technology, COIMBATORE",
		"J.B. institute of technology, Dehradun",
		"University of Petroleum and Energy Studies, Dehradun",
		"Sri Sukhmani Institute Of Engg. & Tech., Derabassi",
		"jayam college of Engineering and technology, Dharmapuri",
		"SDM college of engineering and technology, Dharwad",
		"Chhatrapati Shivaji Institute of Technology , Durg",
		"Aryabhatta Institute of Engineering & Management, Durgapur",
		"University Dhirubhai Ambani Institute of Information and , Gandhinagar",
		"SANJAY MEMORIAL INSTITUTE OF TECHNOLOGY, Ganjam",
		"SRM Institute of Management & Technology, GHAZIABAD",
		"Greater Noida, greater noida institute of technology",
		"Greater Noida, Priyadarshini College Of Computer Sciences",
		"Greater Noida, Sharda University",
		"United College of Engineering & Research, Greater Noida",
		"Rayapati Venkata Ranga Rao & Jagarlamudi Chandramouli College , Guntur",
		"Gandhi Institute Of Engineeering &Technology, Gunupur",
		"Amity University, Gurgaon",
		"Gurgaon Institute Of Technology & Management, Gurgaon",
		"ADHIYAMAAN COLLEGE of ENGINEERING, Hosur",
		"Oriental Institute of Science and Technology, JABALPUR",
		"birla institute of technology extension centre, jaipur",
		"Mesra, Jaipur, Birla Institute of Technology",
		"The LNM Institute of Information Technology, Jaipur",
		"SINGHANIA UNIVERSITY , Jhunjhunu",
		"APOLLO INSTITUTE OF TECHNOLOGY, KANPUR",
		"Dayanand Academy of Management Studies, KANPUR",
		"krishna institute of technology, KANPUR",
		"Krishna Institute of Technology, KANPUR",
		"JYOTISHMATHI INSTITUTE OF TECHNOLOGY & SCIENCE, KARIMNAGAR",
		"knp college of engineering college of engineering karun, karunagapally",
		"CHETTINAD COLLEGE OF ENGINEERING AND TECHNOLOGY, Karur",
		"Model engineering college, Kochi",
		"GURU NANAK INSTITUTE OF TECHNOLOGY, kolkata",
		"M.C. Kejriwal Vidyapeeth Institute of (MCKV), Kolkata",
		"Aditya Institute of Technology and Management, Kotturu",
		"G.Pulla Reddy Engineering College, KURNOOL",
		"Amity University, Lucknow",
		"B.N.College of Engineering & Technology, Lucknow",
		"saroj institute of technology and management, Lucknow",
		"Ludhiana college of engg. & technology, Ludhiana",
		"Lalru Mandi, Distt, Punjab Institute of Engineering and Appli, Malakpur",
		"TA PAI Management Institute Manipal, Manipal",
		"chandigarh engineering college, Mohali",
		"Punjab College of Engineering & Technology, Mohali",
		"KRISHNA INSTITUTE OF MANAGEMENT AND TECHNOLOGY, MORADABAD",
		"Basantsing Institute of Science and J.T Lalvani College of Com, Mumbai",
		"N, Mumbai, Mukesh Patel School Of Technology Management And Engineering",
		"THAKUR INSTITUTE OF AVIATION TECHNOLOGY, Mumbai",
		"audisankara institute of technolgy, Nellore",
		"New Delhi, AMBEDKAR INSTITUTE OF TECHNOLOGY",
		"New Delhi, The Institution of Electronics and Telecommunication Engine",
		"jaypee institute of technology, Noida",
		"JSS Academy of Technical Education, Noida",
		"Aryabhatta Institute of Engineering & Management, Durgapur",
		"lovely professional university, phagwara",
		"Dr.Mahalingam College of Engineering & Technology, Pollachi",
		"St.Ann's engineering college, Prakasam",
		"SHRI RAWATPURA SARKAR INSTITUTE OF TECHNOLOGY, RAIPUR",
		"RAMABAI NAGAR, BHABHA INSTITUTE OF SCIENCE AND TECHNOLOGY",
		"S.A.S.Nagar, National Institiue OF Pharmaceutical Education and resear",
		"Bannari amman institute of technology, Sathyamangalam",
		"Sree vidyanikethan engineering college, Tirupati",
		"Mahakal Institute of Technology and Science, Ujjain",
		"Dr.Pauls Engineering College, ",
		"VISWANADHA INSTITUTE OF TECHNOLOGY AND MANAGEMENT, VISAKHAPATNAM",
		"GITAM University, VISAKHAPATNAM",
		"VITAM COLLEGE OF ENGINEERING, Visakhapatnam",
		"VISAKHA INSTITUTE OF ENGINEERING & TECHNOLOGY, Visakhapatnam",
		"GOVINDRAO WANJARI COLLEGE OF ENGINEERING & TECHNOLOGY, Nagpur",
		"PARALA MAHARAJA ENGINEERING COLLEGE, Berhampur",
		"Sathyabama University, Chennai",
		"Sagar Institute of Research Technology and Science, Bhopal",
		"Velammal Engineering College , Chennai",
		"JAWAHARLAL COLLEGE OF ENGINEERING AND TECHNOLOGY, KERALA",
		"Lakshmi Narain College of Technology (LNCT ), Bhopal",
		"MANAV RACHNA COLLEGE OF ENGINEERING, FARIDABAD",
		"Bhawani Shankar Anangpuriya Institute of Tecnology and Manag, Faridabad",
		"SVKM's ,Narsee Monjee Institute of Management Studies, Mumbai",
		"PARALA MAHARAJA ENGINEERING COLLEGE, ORISSA",
		"SHREE SHANKRACHARYA COLLEGE OF PROFESSIONAL MANAGEMENT AND TECH, RAIPUR",
		"Shri G.S. institute of technology & science, Indore",
		"Greater Noida, sharda university ",
		"MAHAKAL INSTITUTE OF TECHNOLOGY AND MANAGEMENT, UJJAIN",
		"Integral University, Lucknow",
		"Faculty of Management Studies - Institute of Rural , Mansarover, Jaipur",
		"SHERWOOD COLLEGE OF ENGINEERING RESEARCH & TECHNOLOGY , BARABANKI",
		"IMS ENGINEERING COLLEGE, GHAZIABAD",
		"SRI RAM MURTI SMARAK COLLEGE OF ENGENERING AND TECHNOLOGY, BAREILLY",
		"radharaman institute of reseach and technology, Bhopal",
		"Swarna bharathi college of engineering, Andhra Pradesh",
		"LORD KRISHNA COLLEGE OF TECHNOLOGY, INDORE",
		"NIT, DELHI",
		"Sagar Institute of Technology & Management, Barabanki",
		"roorkee institute of technology, Roorke",
		"C.V.RAMAN COLLEGE OF ENGINEERING, BHUBANESWAR",
		"Venkteshwar Institute of Technoology, Indore",
		"CHAMELI DEVI SCHOOL OF ENGINEERING AND MANAGEMENT, INDORE",
		"Greater Noida, Priyadarshani College Of Computer Sciences",
		"Bengal Institute of Technology , Kolkata",
		"Vidya College of Engineering, Merrut",
		"Vishveshwarya Institute of Engineering and Technology, Ghaziabad",
		"PRANVEER SINGH INSTITUTE OF TECHNOLOGY , KANPUR",
		"Mody Institue Of Technology And Science, Laxmangarh",
		"INDIAN INSTITUTE OF TECHNOLOGY, ROPAR",
		"Dvr & Dr.hs mic college of technology, Kanchikacherla",
		"IIT, Mandi",
		"DAYANANDA SAGAR COLLEGE OF ENGINEERING , BANGLORE",
		"ARYAVART INSTITUTE OF TECHNOLOGY AND MANAGEMENT, LUCKNOW",
		"kamla nehru institute of technology, Sultanpur",
		"INSTITUTE OF TECHNOLOGY AND MANAGEMENT, GWALIOR",
		"SHRI RAMSWAROOP MEMORIAL COLLEGE OF ENGINEERING AND MANAGEMEN, LUCKNOW",
		"D.E.I. Technical College, Agra",
		"UNITED INSTITUTE OF TECHNOLOGY, ALLAHABAD",
		"Amity institute of Space And Science technology, Noida",
		"UIET CSJM university , Kanpur",
		" Lucknow, University Of Lucknow",
		"graphic era university, Dehradun",
		"YMCA UNIVERSITY OF SCIENCE AND TECHNOLOGY , FARIDABAD",
		"HI-TECH INSTITUTE OF ENGG. & TECH., GHAZIABAD",
		"Bhilai Institute of Technology, Raipur",
		"Amity School Of Engg. and Tech., New Delhi",
		"Hi-Tech College of Engineering and Technology, Hyderabad",
		"HYDERABAD, MLR INSTITUTE OF TECHNOLOGY, DUNGIGAL",
		"Jaypee University of Engineering and Technology, Guna",
		"PRANVEER SINGH ACADEMY OF TECHNOLOGY, KANPUR",
		"BARKATULLAH UNIVERSITY INSTITUTE OF TECHNOLOGY, BHOPAL",
		"Babu Banarsi Das National Institute Of Technology And Mangeme, Lucknow",
		"CHHATTISGARH.. SHRI SHANKARACHARYA ENGINEERING COLLEGE, BHILAI ",
		"Sanketika Vidya Parishad Engineering College (SVPEC), Vishakapatnam",
		"LAXMIPATI INSTITUTE OF SCIENCE AND TECHNOLOGY, BHOPAL",
		"Gwalior Institute Of Technology and Science (GITS), Gwalior",
		"KALASALINGAM UNIVERSITY, KRISHNAKOIL",
		"SRM UNIVERSITY, KATTANKULATHUR",
		"SALEM-3,TAMIL NADU, AVS ENGINEERING COLLEGE,  AMMAPET",
		"Mandi, Jawahar Lal Nehru Government Engineering College , Sundernagar",
		"JAI NARAIN COLLEGE OF TECHNOLOGY & SCIENCE, BHOPAL",
		"SHRI SHANKARACHARYA ENGINEERING COLLEGE, BHILAI",
		"Nitte Mahalinga Adyantaya Memorial Institute of Technology, Udupi",
		"Indira college of commerce and science, Pune",
		"MANOHARBHAI PATEL INSTITUTE OF ENGINEERING AND TECHNOLOGY, GONDIA",
		"KANPUR, KRISHNA GIRLS ENGINEERING COLLEGE, MANDHANA",
		"Kolkata, Netaji Subash Engineering College Technocity, Garia",
		"Orissa, Synergy College of Engg & Technology, Dhenkanal ",
		"UTTARANCHAL INSTITUE OF TECHNOLOGY, DEHRADUN",
		"Chittorgarh, Rajasthan, Mewar University",
		"Ambedkar Institute of Technology., New Delhi",
		"SAMSKRUTI COLLEGE OF ENGINEERING AND TECHNOLOGY, GHATKESAR",
		"Lovely Professional University,  Phagwara, Punjab",
		"mathura, Sachdeva institute of technology, Farah",
		"Mahatma jyotiba phule rohailkhand university , Bareilly ",
		"P.S.R.ENGINEERING COLLEGE , Virudhnagar",
		"Andhra Pradesh, Kamala institute of technology and science, Karimnagar",
		"b.b.s.college of engineering & technology, Allahabad",
		"Punjab, Gulzar Institutes Of Enginerring and Technology, Ludhiana",
		"Nagaji Institute Of Technology & Management, Gwalior",
		"AL-aman college of engg, Vishakapatnam",
		"NIT, Jamshedpur",
		"JAI NARAIN COLLEGE OF TECHNOLOGY AND SCIENCE, BHOPAL",
		"Rajnandgaon, Chhattisgarh, Yugantar Institute of Technology",
		"Chitkara School of Engineering and Technology, Baddi",
		"Othakkalmandapam,Hindusthan College of Engineering and Tech, Coimbatore",
		"Government Engineering College, Raipur",
		"UNITED COLLEGE OF ENGINEERING AND MANAGEMENT",
		"Sikkim Manipal University, Sikkim",
		"Cape Institute of Technology, Tamilnadu",
		"Patia,Kalinga Institute of Industrial Technology , Bhubaneswar",
		"Maharaja Surajmal Institute Of Technology, New Delhi",
		"Lovely Professional University, Pagwara",
		"HINDUSTAN COLLEGE OF SCIENCE & TECHNOLOGY, MATHURA",
		"KANPUR,ALLEN HOUSE INSTITUTE OF TECHNOLOGY, ROOMA",
		"Modern Institute of Technology Research Centre, Alwar",
		"DPS Azad Nagar, Kanpur",
		"mangalayatan university ",
		"Institute of Engineering And Technology, Lucknow",
		"Netaji Subhas Institute Of Technology, New Delhi",
		"AUSHAPUR(V),GHATKESAR(M), AURORA'S SCIENTIFIC & TECHNOLOGICAL INSTITUT",
		"Mylavaram.krishna district,Andhra pradesh,lakireddy balireddy college ",
		"H.R.Institute of technology, Ghaziabad",
		"JAYPEE INSTITUTE OF INFORMATION TECHNOLOGY, Noida",
		"Kailash Chandra Bansal College of Technology, Bhopal",
		"Bansal Institute of Engineering and Technology, Lucknow",
		"Maharastra,NMIMS' Mukesh Patel School of Technology Management , Dhulia",
		"Northern India Engineering College, New Delhi",
		"Professional Institute of engg. & technology, Raipur",
		"SWAMI PARMANAND COLLEGE OF ENGINEERING &TECHNOLOGY, MOHALI",
		"Allahabad, B.B.S. Colllege of eng. & tech, Phaphamau",
		"Haryana,haryana engineering college, Yamunanagar",
		"CHITKARA SCHOOL OF ENGINEERING AND TECHNOLOGY, BADDI",
		"Shri Ram Murti Smarak Women's College of Engineering and Tech, Bareilly",
		"INDIAN INSTITUTE OF SCIENCE EDUCATION AND RESEARCH, BHOPAL",
		"P.D.E.A'S A.G.AWATE COLLEGE OF ENGINEERING, HADAPSAR",
		"jagannath institute for technology and management, Paralakhemundi",
		"Noida Institute of Engineering and Technology, Greater Noida",
		"JAFFARPUR-NEW DELHI,C.B.P GOVERNMENT ENGINEERING COLLEGE",
		"GODAVARI INSTITUTE OF ENGUNEERING AND TECHNOLGY, RAJAHMUNDRI",
		"Laxmi Narayan Institute Of Technology (LNIT), Gwalior",
		"Goel institute of technology and management, Lucknow",
		"amity university, Lucknow",
		"Dayanand Academy of Management Studies, Kanpur",
		"bharatiya vidya mandir college of technology and management, Gwalior",
		"Global Research institute of Management and Technology",
		"USA,Polytechnic Institute of New York University, New York",
		"SAM College of Engineering and Technology, BHOPAL",
		"Padmasri Dr. B.V RAJU Institute of Technology, Medak",
		"TRUBA INSTITUTE OF ENGINEERING AND INFORMATION TECHNOLOGY, Bhopal",
		"VIGNAN'S LARA INSTITUTE OF TECHNOLOGY AND SCIENCE, VADLAMUDI",
		"Institute of Management Studies, Ghaziabad",
		"MOHALI, KHARAR, GGS COLLEGE OF MODERN TECHNOLOGY",
		"NITTE MEENAKSHI INSTITUTE OF TECHNOLOGY",
		"ORISSA, MODERN ENGINEERING AND MANAGEMENT STUDIES, BALASORE",
		"NIT, Kurukshetra",
		"MOHAN NAGAR, INSTITUTE OF TECHNOLOGY AND SCIENCE, GHAZIABAD",
		"ORISSA, BERHAMPUR, GANDHI ACADEMY OF TECHNOLOGY AND ENGINEERING",
		"Shibpur, Howrah, Bengal Engineering and Science University ",
		"IIT, Bhubaneswar",
		"Radharaman Engg. College, Bhopal",
		"RSR-RCET, Raipur",
		"Feroze Ghandhi Institute of Engineering & Technology, Raibareli",
		"Padmanava College Of Engg., Rourkela",
		"Gwalior, Prestige Institute of Management, Gwalior",
		"shaheed bhagat singh college of engg.and technology, Ferozpur",
		"Lingaya's Institute Of Management & Technology, faridabad",
		"Lingaya's Institute Of Management & Technology, Faridabad",
		"HoshiarpurSSG panjab university regional centre",
		"University Institute of Engineering And Technology(UIET),  Kurukshetra",
		"GURU NANAK DEV UNIVERSITY, AMRITSAR",
		"Raj Kumar Goel Institute of Technology, Ghaziabad",
		"Guru Gram Institute of Aeronautical Engineering and Technol, Faridabad",
		"Sri Ram Engineering College, Chennai",
		"International Institute of Telecom Technology, Pojewal",
		"Lovely Professional University, Punjab",
		"International Institute of Professional Studies , Indore",
		"Sanghvi Innovative Acadmey, Indore",
		"Acropolis Technical Campus, Indore",
		"Jaipur , Vivekananda Institute Of Technology",
		"Patel Institute Of Technology Bhopal, Bhopal",
		"Krishna Institute Of Engineering Technology , Ghaziabad",
		"Maharana Pratap Engineering College , Kanpur",
		"Rangareddy District, Birla Institute Of Technology And Sciences ",
		"Jayamukhi Institute Of Tecnological Sciences , Warangal",
		"Bhilai School Of Engineering , Durg",
		"Srk Institute Of Technology , Vijayawada",
		"Institute Of Engineering And Technology , Jhansi",
		"University Institute Of Technology , Burdwan",
		"Hmr Institute Of Technology And Management , Delhi",
		"Bvm College Of Technology And Management , Gwalior",
		"Sir Padampat Singhania University , Udaipur",
		"A.V.C College Of Engineering , Mayiladuthurai",
		"Saraswati Institute Of Engineering And Technology , Ghaziabad",
		"Tapi Brahmcharyashram Sabha Collage Of Engineering , Surat",
		"Bhagwan Mahavir College Of Engineering And Technology , Surat",
		"Saraswati Institute Of Technology And Management , Lucknow",
		"Engineering & Technolog, Jaipur, International Institute Of Management",
		"Vadlamudi , Guntur, Vignan University",
		"Institute Of Engineering And Management , Kolkata",
		"P.S.R.Engineering College , Sivakasi",
		"Greater Noida, Gautam Buddha University ",
		"Vikrant Institute Of Technology And Management , Gwalior",
		"Iitt College Of Engineering , Nawanshahr",
		"Oriental Engineering College , Jabalpur",
		"Axis Institute Of Technology And Management , Kanpur",
		"Indian Institute Of Space Science And Technology , Thiruvananthapuram",
		"Modi Institute Of Technology And Science , Sikar",
		"Indore , Indore, Malwa Institute Of Technology ",
		"Bipin Tripathi Kumaon Engineering College, Uttarakhand",
		"Vimaljyothi Engineering College Chemperi , Kannur",
		"University Institute Of Technology , Burdwan",
		"St.Johns College Of Engg & Tech , Kurnool",
		"University College Of Engineering , Vizianagaram",
		"R. R. Institute of Modern Technology, Lucknow",
		"Guru Gram Institute Of Aeronautical Engineering And Technol, Faridabad",
		"Indore , Oriental Institutes Of Science And Technology ",
		"Chennai , Ganesh Institute Of Engineering ",
		"Landran , Chandigarh Engineering College ",
		"Uma Nath Singh Institute Of Engineering. & Technology , Jaunpur ",
		"West Bengal , Netaji Subhas Engineering College ",
		"Bhopal , Radharaman Institute Of Technology And Science ",
		"Lakshmi Narain College Of Technology And Science , Bhopal",
		"Gwalior, Rustam Ji Institute Of Technology, Tekanpur",
		"New Prince Shri Bhavani College Of Engineering And Technology, Chennai",
		"S.V Institute Of Engineering And Technology, Rangareddy",
		"Jawahar Lal Nehru Government Engineering College, Sundernagar",
		"Amity Institute Of Nano Technology, Noida",
		"Maharishi Markandeshwar University, Mullana",
		"Rayat And Bahara Institute Of Engg. And Biotech , Mohali",
		"K.N.G.D. MODI ENGINEERING COLLEGE, Modinagar",
		"P.S.R.Engineering College, Sivakasi",
		"Central University Of Rajasthan, Ajmer",
		"Arya College Of Engineering And Research Centre, Jaipur",
		"Prabhat Engineering College, Kanpur",
		"Darbhanga College of Engineering , Darbhanga",
		"KCT Engineering College, Gulbarga",
		"Chamelidevi Group Of Institutions, Indore",
		"Ravi Shanker Institute Of Technology And Management, Jabalpur",
		"University College Of Engineering And Technology, Hazaribag",
		"TRR Womens College Of Engineering, Patancheru",
		"Sir Chhotu Ram Institute Of Engineering And Technology, Meerut",
		"Amity Institute Of Aerospace Engineering, Noida",
		"Sreenivasa Institute Of Technology And Management Studies, Chittoor",
		"Central India Institute Of Technology, Indore",
		"KCB Technical Acadamy, Indore",
		"JnanaVikas Institute Of Technology, Bangalore",
		"S V Institute Of Computer Studies, Kadi",
		"Mothadaka, Guntur, Chalapathi Institute Of Technology",
		"Purushottam Institute Of Engineering & Technology, Rourkela",
		"Vizag Institute Of Technology, Visakhapatnam",
		"Institute Of Public Enterprise, Hyderabad",
		"Khandelwal College Of Management Science And Technology, Bareilly",
		"Dr C.V. Raman University, Bilaspur",
		"Zakir Hussain College Of Engineering & Technology, Aligarh",
		"Bhagwant University, Ajmer",
		"Late Ramoti Devi Institute Of Engineering, Ujjain",
		"Rajiv Gandhi University Of Knowledge Technologies, Hyderabad",
		"Centre For Converging Technologies , Jaipur",
		"Government College Of Engineering Kalahandi, Kalahandi",
		"Keshav Memorial Institute Of Technology, Hyderabad",
		"Gwalior Engineering College, Gwalior",
		"Ambalika Institute Of Management And Technology, Lucknow",
		"Gyan Ganga Institute Of Technology And Management, Bhopal",
		"Calcutta Institute Of Technology, Kolkata",
		"Rajiv Gandhi University Of Knowledge Technologies, Nuzvid",
		"Vivekanandha College Of Technology For Women, Tiruchengode",
		"Manav Rachna International University, Faridabad",
		"Shri Lal Bahadur Shashtri Engineering College, Jodhpur",
		"B M S Institute Of Technology, Bangalore",
		"Jagannath University, Jaipur",
		"Yawatmal , Jagadambha College Of Engineering and Technology",
		"Mahabub Nagar, Jayaprakash Narayan College Of Engineering",
		"Pilani, Dubai Campus, Birla Institute Of Technology And Science",
		"Nagpur , Kavikulguru Institute Of Technology And Science",
		"NIT, Uttarakhand",
		"Babu Banarasi Das Educational Society's Group Of Educational , Lucknow",
		"Manyawar Kansiram Engineering College Of Information Technol, Azamgarh",
		"Maharana Institute Of Professional Studies, Kanpur",
		"Vedant College Of Engineering & Technology, Bundi",
		"College Of Engineering, Pune",
		"DNS College Of Engineering And Technology, Amroha",
		"Mewar University, Chittorgarh",
		"Shree Shankracharya College Of Engineering And Technology, Durg",
		"JK Institute Of Engineering, Bilaspur",
		"Graphic Era University, Dehradun",
		"Lakshmi Narayan Academy Of Technology, Gwalior",
		"Anand Nagar, Kalasalingam University",
		"Babu Banarasi Das Educational Society's Group Of Institutions, Lucknow",
		"Malla Reddy Engineering College For Women, Hyderabad",
		"Velammal Engineering College, Chennai",
		"Bomma Institue Of Technolgy And Science, Khammam",
		"Dayanand Dinanath Institute Of Technology, Unnao",
		"Gurukul Group Of Institutions, Bibinagar",
		"Indus Institute of Technology & Management, Kanpur",
		"Babu Banarsi Das Northern India Institute Of Technology, Lucknow",
		"KCC Institute Of Technology And Management, Greater Noida",
		"ShambhuNath Institute Of Engineering And Technology, Allahabad",
		"JNTUH College Of Engineering, Karimnagar",
		"Vishwakarma Institute Of Information Technology, Pune",
		"Laqshya Institue Of Technolgy And Science, Khammam",
		"Vidyavardhini's College Of Engineering & Technology, Vasai",
		"Pandit Deendayal Petroleum University, Gandhinagar",
		"Government Engineering College, Modasa",
		"Atria Institute Of Technology, Bangalore",
		"GRD Institute Of Management And Technology, Dehradun",
		"St. Peters Engineering College, Hyderabad",
		"University College Of Engineering , Kota",
		"ABES IT Group of Institutions Campus-2, Ghaziabad",
		"Rayat & Bahra Institute Of Engineering & Bio-Technology, Sahauran",
		"Shri Siddeshwar Shikshan MandalýS College Of Architectur, Solapur",
		"Sunrise Institute Of Engineering Technology And Management, Unnao",
		"Bhai Gurdas Institute Of Engineering & Technology, Patiala",
		"Rewa Institute Of Technology, Rewa",
		"Sathyabama University, Chennai",
		"V.S.B Engineering College, Karur",
		"Bhagwan Mahaveer Institute Of Engineering & Technology, Sonipat",
		"Periyar Maniammai University, Periyar nagar",
		"Periyar nagar, Periyar Maniammai University",
		"Maharshi Dayanand University, Rohtak",
		"Rashtriya Vidyalaya College Of Engineering, Bangalore",
		"S.V Institute of Engineering And Technology, Eathbarpally",
		"Swift Institute Of Engineering And Technology, Rajpura",
		"National Institute of Technology, Puducherry",
		"Velalar College Of Engineerig And Technology, Erode",
		"Saranathan College Of Engineering, Trichy",
		"Ace Engineering College, Ghatkesar",
		"L.D Engineering College, Ahmedabad",
		"City Womens College Of Enggineering and Technology, Hyderabad",
		"Hindu College Of Engineering Sonipat , Sonipat",
		"Shri Andal Alagar College of Engineering, Mamandur",
		"Noida Institute Of Enggineering and Technology, Greater Noida",
		"SVNIT College, Sagar",
		"Vel Tech High Tech Dr.Rangarajan Dr. Sakunthala Engineering C, Chennai",
		"FORE School of Management, New Delhi",
		"Modinagar Institute Of Technology Modinagar, Ghaziabad",
		"Babaria Institute Of Technology, Varnama",
		"Guru Tegh Bahadur Institute of Technology, New Delhi",
		"JK Lakshmipat University, Jaipur",
		"International Institute Of Management Engineering & Technolog, Jaipur ",
		"Rajarshi Rananjay Sinh Institute Of Management & Techn, Rajarshi Nagar",
		"The Institution of Electronics and Telecommunication Engine, New Delhi",
		"Vkr.Vnb&Agk Engineering Colleage , Gudivada ",
		"Ganeshi Lal Bajaj Institute of Technology and Managemen, Greater Noida",
		"Indian Institute Of Technology, Ropar",
		"VIT University Chennai Campus, Chennai",
		"Vivekananda Education Society's Institute Of Technology, Mumbai",
		"Seth Jai Prakash mukand Lal Institute of Engg and Technology, Radaur",
		"Jp University Of Information Technology, Waknaghat",
		"National Institute of Fashion Technology, New Delhi",
		"The Institute Of Chartered Financial Analysts Of India Univer, Jaipur",
		"Government College of Engineering, Jalgaon",
		"Perm State University, Russia",
		"Alexandria University, Faculty of Engineering, Egypt",
		"Vinnytsia National Technical University, Ukraine",
		"Indian Institute Of Technology, Indore",
		"Adyghe State University, Pervomayskaya",
		"Bengal College Of Engineering & Technology, Kolkata",
		"Nitte Mahalinga Adyanthayaya Memorial Institute of Technology, Nitte",
		"Indian Institute Of Science Education And Research, Thiruvananthapuram",
		"Bangladesh University of Engineering and Technology, Dhaka",
		"Rajiv Gandhi Institute of Technology, Kottayam",
		"UFPE, Brazil",
		"Federal Institute of Science And Technology, Kerala",
		"PA college of Engineering, Mangalore",
		"Vivekananda Inst.Of Technology, Bhubaneswar",
		"Zhejiang University, China",
		"AES Institute of Computer Studies, Ahmedabad",
		"Narula Institute of Technology, Kolkata",
		"Instituto Tecnolýgico de Chilpancingo, Mexico",
		"Gandhinagar, Institute of Technology , Nirma University",
		"B. P. Poddar Institute Of Technology, Kolkata",
		"Bhartiya Vidyapeeth's College Of Engineering, New Delhi",
		"Comilla University, Bangladesh",
		"Chandigarh Group Of Colleges, Mohali",
		"Bhanu Nagar, Mahatma Gandhi Institute Of Technical Education And Resea",
		"Malwa Institute of Technology and Management, Gwalior",
		"Institute of Applied Mathematics and Mechanics, Ukraine",
		"R G Kar Medical College, Kolkata",
		"Hyderabad, St. Martinse Engineering College"
	);
	
	$source = preg_grep('/'.$term.'/i', $colleges);
	if(count($source) > 50)
		$source = array_slice($source, 0, 50);
	
	$result = array();
	
	foreach($source as $value)
		array_push($result, $value);
	
	echo json_encode($colleges);
	exit;
	
?>
